;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        cperl-electric-backspace
        cperl-electric-rparen
        cperl-electric-semi
        cperl-electric-terminator
        cua-paste
        delete-horizontal-space
        fastnav-jump-to-char-forward
        forward-sexp
        isearch-abort
        kill-sexp
        match-paren
        nxml-electric-slash
        paredit-backward-barf-sexp
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        tempo-x-space
        transpose-sexps
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        isearch-forward-regexp
        ))
