;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        cperl-electric-backspace
        cperl-electric-brace
        cperl-electric-lbrace
        cperl-electric-paren
        cperl-electric-rparen
        cperl-electric-semi
        cperl-electric-terminator
        cua-paste
        delete-horizontal-space
        fastnav-jump-to-char-forward
        forward-sexp
        insert-register
        isearch-abort
        isearch-printing-char
        kill-sexp
        match-paren
        nxml-electric-slash
        paredit-backslash
        paredit-backward-barf-sexp
        paredit-close-round-and-newline
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-meta-doublequote
        paredit-open-round
        paredit-wrap-round
        pp-eval-last-sexp
        smarter-move-beginning-of-line
        smex
        tempo-x-space
        transpose-sexps
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        isearch-forward-regexp
        kmacro-end-or-call-macro
        reindent-then-newline-and-indent
        smart-open-line-above
        ))
