(deftheme pdc-zenburn
  "Created 2013-10-30.")

(defvar zenburn-fg "#dcdccc")
(defvar zenburn-fg-1 "#656555")
(defvar zenburn-bg-1 "#2b2b2b")
(defvar zenburn-bg-05 "#383838")
(defvar zenburn-bg "#3f3f3f")
(defvar zenburn-bg+1 "#4f4f4f")
(defvar zenburn-bg+2 "#5f5f5f")
(defvar zenburn-bg+3 "#6f6f6f")
(defvar zenburn-red+1 "#dca3a3")
(defvar zenburn-red "#cc9393")
(defvar zenburn-red-1 "#bc8383")
(defvar zenburn-red-2 "#ac7373")
(defvar zenburn-red-3 "#9c6363")
(defvar zenburn-red-4 "#8c5353")
(defvar zenburn-orange "#dfaf8f")
(defvar zenburn-yellow "#f0dfaf")
(defvar zenburn-yellow-1 "#e0cf9f")
(defvar zenburn-yellow-2 "#d0bf8f")
(defvar zenburn-green-1 "#5f7f5f")
(defvar zenburn-green "#7f9f7f")
(defvar zenburn-green+1 "#8fb28f")
(defvar zenburn-green+2 "#9fc59f")
(defvar zenburn-green+3 "#afd8af")
(defvar zenburn-green+4 "#bfebbf")
(defvar zenburn-cyan "#93e0e3")
(defvar zenburn-blue+1 "#94bff3")
(defvar zenburn-blue "#8cd0d3")
(defvar zenburn-blue-1 "#7cb8bb")
(defvar zenburn-blue-2 "#6ca0a3")
(defvar zenburn-blue-3 "#5c888b")
(defvar zenburn-blue-4 "#4c7073")
(defvar zenburn-blue-5 "#366060")
(defvar zenburn-magenta "#dc8cc3")
(defvar zenburn-violet  "#6c71c4")
(defvar zenburn-region  "#7f073f")

(custom-theme-set-variables
 'pdc-zenburn
 `(custom-safe-themes (quote
 ("4c9ba94db23a0a3dea88ee80f41d9478c151b07cb6640b33bfc38be7c2415cc4"
 default)))
 '(indent-tabs-mode nil)
 '(whitespace-action (quote (auto-cleanup)))
 '(whitespace-line-column nil)
 '(whitespace-style (quote (quote (quote (tabs trailing lines-tail space-after-tab empty)))))
 '(ansi-color-names-vector ["#3f3f3f" "#cc9393" "#7f9f7f" "#f0dfaf" "#8cd0d3"
 "#dc8cc3" "#93e0e3" "#dcdccc"])
 '(zenburn-fg "#dcdccc")
 '(zenburn-fg-1 "#656555")
 '(zenburn-bg-1 "#2b2b2b")
 '(zenburn-bg-05 "#383838")
 '(zenburn-bg "#3f3f3f")
 '(zenburn-bg+1 "#4f4f4f")
 '(zenburn-bg+2 "#5f5f5f")
 '(zenburn-bg+3 "#6f6f6f")
 '(zenburn-red+1 "#dca3a3")
 '(zenburn-red "#cc9393")
 '(zenburn-red-1 "#bc8383")
 '(zenburn-red-2 "#ac7373")
 '(zenburn-red-3 "#9c6363")
 '(zenburn-red-4 "#8c5353")
 '(zenburn-orange "#dfaf8f")
 '(zenburn-yellow "#f0dfaf")
 '(zenburn-yellow-1 "#e0cf9f")
 '(zenburn-yellow-2 "#d0bf8f")
 '(zenburn-green-1 "#5f7f5f")
 '(zenburn-green "#7f9f7f")
 '(zenburn-green+1 "#8fb28f")
 '(zenburn-green+2 "#9fc59f")
 '(zenburn-green+3 "#afd8af")
 '(zenburn-green+4 "#bfebbf")
 '(zenburn-cyan "#93e0e3")
 '(zenburn-blue+1 "#94bff3")
 '(zenburn-blue "#8cd0d3")
 '(zenburn-blue-1 "#7cb8bb")
 '(zenburn-blue-2 "#6ca0a3")
 '(zenburn-blue-3 "#5c888b")
 '(zenburn-blue-4 "#4c7073")
 '(zenburn-blue-5 "#366060")
 '(zenburn-magenta "#dc8cc3")
 '(zenburn-violet  "#6c71c4")
 '(zenburn-region  "#7f073f"))

(custom-theme-set-faces
 'pdc-zenburn
; `(custom-group-tag ((t (:height 1.2 :weight bold :foreground ,zenburn-red+1 :inherit variable-pitch))))
 `(button ((t (:underline t))))
 `(link ((t (:foreground ,zenburn-yellow :underline t :weight bold))))
 `(link-visited ((t (:foreground ,zenburn-yellow-2 :underline t :weight normal))))
 `(cursor ((t (:foreground ,zenburn-fg :background "white"))))
 `(escape-glyph ((t (:foreground ,zenburn-yellow :bold t))))
 `(fringe ((t (:foreground ,zenburn-fg :background ,zenburn-bg+1))))
 `(header-line ((t (:foreground ,zenburn-yellow :background ,zenburn-bg-1 :box (:line-width -1 :style released-button)))))
 `(highlight ((t (:background "#383838"))))
 `(success ((t (:foreground ,zenburn-green :weight bold))))
 `(warning ((t (:foreground ,zenburn-orange :weight bold))))
 `(compilation-column-face ((t (:foreground ,zenburn-yellow))))
 `(compilation-enter-directory-face ((t (:foreground ,zenburn-green))))
 `(compilation-error-face ((t (:foreground ,zenburn-red-1 :weight bold :underline t))))
 `(compilation-face ((t (:foreground ,zenburn-fg))))
 `(compilation-info-face ((t (:foreground ,zenburn-blue))))
 `(compilation-info ((t (:foreground ,zenburn-green+4 :underline t))))
 `(compilation-leave-directory-face ((t (:foreground ,zenburn-green))))
 `(compilation-line-face ((t (:foreground ,zenburn-yellow))))
 `(compilation-line-number ((t (:foreground ,zenburn-yellow))))
 `(compilation-message-face ((t (:foreground ,zenburn-blue))))
 `(compilation-warning-face ((t (:foreground ,zenburn-orange :weight bold :underline t))))
 `(compilation-mode-line-exit ((t (:foreground ,zenburn-green+2 :weight bold))))
 `(compilation-mode-line-fail ((t (:foreground ,zenburn-red :weight bold))))
 `(compilation-mode-line-run ((t (:foreground ,zenburn-yellow :weight bold))))
 `(confluence-code-face ((t (:inherit zenburn-lowlight-2))) t)
 `(confluence-panel-face ((t (:inherit zenburn-primary-2))) t)
 `(hi-edebug-x-debug-line ((t (:inherit zenburn-highlight-subtle))))
 `(hi-edebug-x-stop ((t (:background "#2e4440"))))
 `(latex-mode-default ((t (:inherit autoface-default :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 140 :width normal :family "Lucida Grande"))) t)
 `(magit-item-highlight ((t (:inherit zenburn-highlight-damp))))
 `(mm/master-face ((t (:background "#2e3330"))))
 `(mm/mirror-face ((t (:background "#2e3330"))))
 `(org-clock-overlay ((t (:background ,zenburn-blue-5))))
 `(org-mode-default ((t (:inherit autoface-default :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 140 :width normal :family "TheSansMonoCd Office"))) t)
 `(text-mode-default ((t (:inherit autoface-default :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 140 :width normal :family "TheSansMonoCd Office"))) t) '(cperl-array-face ((t (:inherit font-lock-variable-name :weight bold))))
 `(cperl-hash-face ((t (:inherit font-lock-variable-name-face))))
 `(custom-button
   ((t (:inherit fancy-widget-button))))
 `(custom-button-pressed
   ((t (:inherit fancy-widget-button-pressed))))
 `(custom-changed
   ((t (:inherit zenburn-blue))))
 `(custom-comment
   ((t (:inherit font-lock-doc))))
 `(custom-comment-tag
   ((t (:inherit font-lock-doc))))
 `(custom-documentation
   ((t (:inherit font-lock-doc))))
 `(custom-link
   ((t (:inherit zenburn-yellow :underline t))))
 `(custom-tag
   ((t (:inherit zenburn-primary-2))))
 `(custom-group-tag
   ((t (:inherit (zenburn-primary-1)))))
 `(custom-group-tag-1
   ((t (:inherit zenburn-primary-4))))
 `(custom-invalid
   ((t (:inherit font-lock-warning))))
 `(custom-modified
   ((t (:inherit zenburn-primary-3))))
 `(custom-rogue
   ((t (:inhrit font-lock-warning))))
 `(custom-saved
   ((t (:underline t))))
 `(custom-set
   ((t (:inverse-video t :inherit zenburn-blue))))
 `(custom-state
   ((t (:inherit font-lock-comment))))
 `(custom-variable-button
   ((t (:weight bold :underline t))))
 `(custom-variable-tag
   ((t (:inherit zenburn-primary-2))))

 `(grep-context-face ((t (:foreground ,zenburn-fg))))
 `(grep-error-face ((t (:foreground ,zenburn-red-1 :weight bold :underline t))))
 `(grep-hit-face ((t (:foreground ,zenburn-blue))))
 `(grep-match-face ((t (:foreground ,zenburn-orange :weight bold))))
 `(match ((t (:background ,zenburn-bg-1 :foreground ,zenburn-orange :weight bold))))
 `(isearch ((t (:foreground ,zenburn-yellow-2 :weight bold :background ,zenburn-bg-1))))
 `(isearch-fail ((t (:foreground ,zenburn-fg :background ,zenburn-red-4))))
 `(lazy-highlight ((t (:foreground ,zenburn-yellow-2 :weight bold :background "#383838"))))
 `(menu ((t (:foreground ,zenburn-fg :background "#3f3f3f"))))
 `(minibuffer-prompt ((t (:foreground ,zenburn-yellow))))
 `(mode-line ((((class color) (min-colors 89)) (:foreground ,zenburn-green+1 :background ,zenburn-bg-1 :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 `(mode-line-buffer-id ((t (:foreground ,zenburn-yellow :weight bold))))
 `(mode-line-inactive ((t (:foreground ,zenburn-green-1 :background "#383838" :box (:line-width -1 :style released-button)))))
 `(region ((((class color) (min-colors 89)) (:background "#7f073f")) (t :inverse-video t)))
 `(secondary-selection ((t (:background ,zenburn-orange))))
 `(trailing-whitespace ((t (:background ,zenburn-red))))
 `(vertical-border ((t (:foreground ,zenburn-fg))))
 `(font-lock-builtin-face ((t (:foreground ,zenburn-cyan))))
 `(font-lock-comment-face ((t (:foreground ,zenburn-green))))
 `(font-lock-comment-delimiter-face ((t (:foreground ,zenburn-green))))
 `(font-lock-constant-face ((t (:foreground ,zenburn-green+4))))
 `(font-lock-doc-face ((t (:foreground ,zenburn-green+1))))
 `(font-lock-doc-string-face ((t (:foreground ,zenburn-blue-2))))
 `(font-lock-function-name-face ((t (:foreground ,zenburn-blue))))
 `(font-lock-keyword-face ((t (:foreground ,zenburn-yellow :weight bold))))
 `(font-lock-negation-char-face ((t (:foreground ,zenburn-fg))))
 `(font-lock-preprocessor-face ((t (:foreground ,zenburn-blue+1))))
 `(font-lock-string-face ((t (:foreground ,zenburn-red))))
 `(font-lock-type-face ((t (:foreground ,zenburn-blue-1))))
 `(font-lock-variable-name-face ((t (:foreground ,zenburn-orange))))
 `(font-lock-warning-face ((t (:foreground ,zenburn-yellow-2 :weight bold))))
 `(c-annotation-face ((t (:inherit font-lock-constant-face))))
 `(newsticker-date-face ((t (:foreground ,zenburn-fg))))
 `(newsticker-default-face ((t (:foreground ,zenburn-fg))))
 `(newsticker-enclosure-face ((t (:foreground ,zenburn-green+3))))
 `(newsticker-extra-face ((t (:foreground ,zenburn-bg+2 :height 0.8))))
 `(newsticker-feed-face ((t (:foreground ,zenburn-fg))))
 `(newsticker-immortal-item-face ((t (:foreground ,zenburn-green))))
 `(newsticker-new-item-face ((t (:foreground ,zenburn-blue))))
 `(newsticker-obsolete-item-face ((t (:foreground ,zenburn-red))))
 `(newsticker-old-item-face ((t (:foreground "#6f6f6f"))))
 `(newsticker-statistics-face ((t (:foreground ,zenburn-fg))))
 `(newsticker-treeview-face ((t (:foreground ,zenburn-fg))))
 `(newsticker-treeview-immortal-face ((t (:foreground ,zenburn-green))))
 `(newsticker-treeview-listwindow-face ((t (:foreground ,zenburn-fg))))
 `(newsticker-treeview-new-face ((t (:foreground ,zenburn-blue :weight bold))))
 `(newsticker-treeview-obsolete-face ((t (:foreground ,zenburn-red))))
 `(newsticker-treeview-old-face ((t (:foreground "#6f6f6f"))))
 `(newsticker-treeview-selection-face ((t (:foreground ,zenburn-yellow))))
 `(ace-jump-face-background ((t (:foreground "#656555" :background "#3f3f3f" :inverse-video nil))))
 `(ace-jump-face-foreground ((t (:foreground ,zenburn-green+2 :background "#3f3f3f" :inverse-video nil))))
 `(ack-separator ((t (:foreground ,zenburn-fg))))
 `(ack-file ((t (:foreground ,zenburn-blue))))
 `(ack-line ((t (:foreground ,zenburn-yellow))))
 `(ack-match ((t (:foreground ,zenburn-orange :background ,zenburn-bg-1 :weight bold))))
 `(font-latex-bold ((t (:inherit bold))))
 `(font-latex-warning ((t (:inherit font-lock-warning))))
 `(font-latex-sedate ((t (:foreground ,zenburn-yellow :weight bold))))
 `(font-latex-title-4 ((t (:inherit variable-pitch :weight bold))))
 `(ac-candidate-face ((t (:background "#6f6f6f" :foreground "black"))))
 `(ac-selection-face ((t (:background ,zenburn-blue-4 :foreground ,zenburn-fg))))
 `(popup-tip-face ((t (:background ,zenburn-yellow-2 :foreground "black"))))
 `(popup-scroll-bar-foreground-face ((t (:background ,zenburn-blue-5))))
 `(popup-scroll-bar-background-face ((t (:background ,zenburn-bg-1))))
 `(popup-isearch-match ((t (:background "#3f3f3f" :foreground ,zenburn-fg))))
 `(android-mode-debug-face ((t (:foreground ,zenburn-green+1))))
 `(android-mode-error-face ((t (:foreground ,zenburn-orange :weight bold))))
 `(android-mode-info-face ((t (:foreground ,zenburn-fg))))
 `(android-mode-verbose-face ((t (:foreground ,zenburn-green))))
 `(android-mode-warning-face ((t (:foreground ,zenburn-yellow))))
 `(bm-face ((t (:background ,zenburn-yellow-1 :foreground "#3f3f3f"))))
 `(bm-fringe-face ((t (:background ,zenburn-yellow-1 :foreground "#3f3f3f"))))
 `(bm-fringe-persistent-face ((t (:background ,zenburn-green-1 :foreground "#3f3f3f"))))
 `(bm-persistent-face ((t (:background ,zenburn-green-1 :foreground "#3f3f3f"))))
 `(clojure-test-failure-face ((t (:foreground ,zenburn-orange :weight bold :underline t))))
 `(clojure-test-error-face ((t (:foreground ,zenburn-red :weight bold :underline t))))
 `(clojure-test-success-face ((t (:foreground ,zenburn-green+1 :weight bold :underline t))))
 `(ctbl:face-cell-select ((t (:background ,zenburn-blue :foreground "#3f3f3f"))))
 `(ctbl:face-continue-bar ((t (:background "#383838" :foreground "#3f3f3f"))))
 `(ctbl:face-row-select ((t (:background ,zenburn-cyan :foreground "#3f3f3f"))))


 `(diff-added ((t (:inherit zenburn-primary-3))))
 `(diff-context ((t (:inherit font-lock-comment))))
 `(diff-file-header ((t (:inherit bold))))
 `(diff-header ((t (:inherit zenburn-highlight-subtle))))
 `(diff-hunk-header ((t (:inherit zenburn-highlight-subtle))))
 `(diff-index ((t (:inherit bold))))
 `(diff-refine-change ((t (:inherit zenburn-background-2))))
 `(diff-removed ((t (:inherit zenburn-blue))))


 ;; '(diff-added ((((class color) (min-colors 89)) (:foreground ,zenburn-green+4 :background nil)) (t (:foreground ,zenburn-green-1 :background nil))))
 ;; '(diff-changed ((t (:foreground ,zenburn-yellow))))
 ;; '(diff-removed ((((class color) (min-colors 89)) (:foreground ,zenburn-red :background nil)) (t (:foreground ,zenburn-red-3 :background nil))))
 ;; '(diff-refine-added ((t :inherit diff-added :weight bold)))
 ;; '(diff-refine-change ((t :inherit diff-changed :weight bold)))
 ;; '(diff-refine-removed ((t :inherit diff-removed :weight bold)))
 ;; '(diff-header ((t (:inherit zenburn-highlight-subtle))))

 ;; '(diff-header ((((class color) (min-colors 89)) (:background ,zenburn-bg+2)) (t (:background ,zenburn-fg :foreground "#3f3f3f"))))
 ;; '(diff-file-header ((((class color) (min-colors 89)) (:background ,zenburn-bg+2 :foreground ,zenburn-fg :bold t)) (t (:background ,zenburn-fg :foreground "#3f3f3f" :bold t))))
 `(diredp-display-msg ((t (:foreground ,zenburn-blue))))
 `(diredp-compressed-file-suffix ((t (:foreground ,zenburn-orange))))
 `(diredp-date-time ((t (:foreground ,zenburn-magenta))))
 `(diredp-deletion ((t (:foreground ,zenburn-yellow))))
 `(diredp-deletion-file-name ((t (:foreground ,zenburn-red))))
 `(diredp-dir-heading ((t (:foreground ,zenburn-blue :background ,zenburn-bg-1))))
 `(diredp-dir-priv ((t (:foreground ,zenburn-cyan))))
 `(diredp-exec-priv ((t (:foreground ,zenburn-red))))
 `(diredp-executable-tag ((t (:foreground ,zenburn-green+1))))
 `(diredp-file-name ((t (:foreground ,zenburn-blue))))
 `(diredp-file-suffix ((t (:foreground ,zenburn-green))))
 `(diredp-flag-mark ((t (:foreground ,zenburn-yellow))))
 `(diredp-flag-mark-line ((t (:foreground ,zenburn-orange))))
 `(diredp-ignored-file-name ((t (:foreground ,zenburn-red))))
 `(diredp-link-priv ((t (:foreground ,zenburn-yellow))))
 `(diredp-mode-line-flagged ((t (:foreground ,zenburn-yellow))))
 `(diredp-mode-line-marked ((t (:foreground ,zenburn-orange))))
 `(diredp-no-priv ((t (:foreground ,zenburn-fg))))
 `(diredp-number ((t (:foreground ,zenburn-green+1))))
 `(diredp-other-priv ((t (:foreground ,zenburn-yellow-1))))
 `(diredp-rare-priv ((t (:foreground ,zenburn-red-1))))
 `(diredp-read-priv ((t (:foreground ,zenburn-green-1))))
 `(diredp-symlink ((t (:foreground ,zenburn-yellow))))
 `(diredp-write-priv ((t (:foreground ,zenburn-magenta))))
 `(ert-test-result-expected ((t (:foreground ,zenburn-green+4 :background "#3f3f3f"))))
 `(ert-test-result-unexpected ((t (:foreground ,zenburn-red :background "#3f3f3f"))))
 `(eshell-prompt ((t (:foreground ,zenburn-yellow :weight bold))))
 `(eshell-ls-archive ((t (:foreground ,zenburn-red-1 :weight bold))))
 `(eshell-ls-backup ((t (:inherit font-lock-comment))))
 `(eshell-ls-clutter ((t (:inherit font-lock-comment))))
 `(eshell-ls-directory ((t (:foreground ,zenburn-blue+1 :weight bold))))
 `(eshell-ls-executable ((t (:foreground ,zenburn-red+1 :weight bold))))
 `(eshell-ls-unreadable ((t (:foreground ,zenburn-fg))))
 `(eshell-ls-missing ((t (:inherit font-lock-warning))))
 `(eshell-ls-product ((t (:inherit font-lock-doc))))
 `(eshell-ls-special ((t (:foreground ,zenburn-yellow :weight bold))))
 `(eshell-ls-symlink ((t (:foreground ,zenburn-cyan :weight bold))))
 `(flycheck-error-face ((t (:foreground ,zenburn-red-1 :weight bold :underline t))))
 `(flycheck-warning-face ((t (:foreground ,zenburn-orange :weight bold :underline t))))
 `(flymake-errline ((t (:foreground ,zenburn-red-1 :weight bold :underline t))))
 `(flymake-warnline ((t (:foreground ,zenburn-orange :weight bold :underline t))))
 `(flyspell-duplicate ((t (:foreground ,zenburn-orange :weight bold :underline t))))
 `(flyspell-incorrect ((t (:foreground ,zenburn-red-1 :weight bold :underline t))))
 `(erc-action-face ((t (:inherit erc-default-face))))
 `(erc-bold-face ((t (:weight bold))))
 `(erc-current-nick-face ((t (:foreground ,zenburn-blue :weight bold))))
 `(erc-dangerous-host-face ((t (:inherit font-lock-warning))))
 `(erc-default-face ((t (:foreground ,zenburn-fg))))
 `(erc-direct-msg-face ((t (:inherit erc-default))))
 `(erc-error-face ((t (:inherit font-lock-warning))))
 `(erc-fool-face ((t (:inherit erc-default))))
 `(erc-highlight-face ((t (:inherit hover-highlight))))
 `(erc-input-face ((t (:foreground ,zenburn-yellow))))
 `(erc-keyword-face ((t (:foreground ,zenburn-blue :weight bold))))
 `(erc-nick-default-face ((t (:foreground ,zenburn-yellow :weight bold))))
 `(erc-my-nick-face ((t (:foreground ,zenburn-red :weight bold))))
 `(erc-nick-msg-face ((t (:inherit erc-default))))
 `(erc-notice-face ((t (:foreground ,zenburn-green))))
 `(erc-pal-face ((t (:foreground ,zenburn-orange :weight bold))))
 `(erc-prompt-face ((t (:foreground ,zenburn-orange :background "#3f3f3f" :weight bold))))
 `(erc-timestamp-face ((t (:foreground ,zenburn-green+1))))
 `(erc-underline-face ((t (:underline t))))
 `(git-gutter:added ((t (:foreground ,zenburn-green :weight bold :inverse-video t))))
 `(git-gutter:deleted ((t (:foreground ,zenburn-red :weight bold :inverse-video t))))
 `(git-gutter:modified ((t (:foreground ,zenburn-magenta :weight bold :inverse-video t))))
 `(git-gutter:unchanged ((t (:foreground ,zenburn-fg :weight bold :inverse-video t))))
 `(git-gutter-fr:added ((t (:foreground ,zenburn-green :weight bold))))
 `(git-gutter-fr:deleted ((t (:foreground ,zenburn-red :weight bold))))
 `(git-gutter-fr:modified ((t (:foreground ,zenburn-magenta :weight bold))))
 `(gnus-group-mail-1 ((t (:bold t :inherit gnus-group-mail-1-empty))))
 `(gnus-group-mail-1-empty ((t (:inherit gnus-group-news-1-empty))))
 `(gnus-group-mail-2 ((t (:bold t :inherit gnus-group-mail-2-empty))))
 `(gnus-group-mail-2-empty ((t (:inherit gnus-group-news-2-empty))))
 `(gnus-group-mail-3 ((t (:bold t :inherit gnus-group-mail-3-empty))))
 `(gnus-group-mail-3-empty ((t (:inherit gnus-group-news-3-empty))))
 `(gnus-group-mail-4 ((t (:bold t :inherit gnus-group-mail-4-empty))))
 `(gnus-group-mail-4-empty ((t (:inherit gnus-group-news-4-empty))))
 `(gnus-group-mail-5 ((t (:bold t :inherit gnus-group-mail-5-empty))))
 `(gnus-group-mail-5-empty ((t (:inherit gnus-group-news-5-empty))))
 `(gnus-group-mail-6 ((t (:bold t :inherit gnus-group-mail-6-empty))))
 `(gnus-group-mail-6-empty ((t (:inherit gnus-group-news-6-empty))))
 `(gnus-group-mail-low ((t (:bold t :inherit gnus-group-mail-low-empty))))
 `(gnus-group-mail-low-empty ((t (:inherit gnus-group-news-low-empty))))
 `(gnus-group-news-1 ((t (:bold t :inherit gnus-group-news-1-empty))))
 `(gnus-group-news-2 ((t (:bold t :inherit gnus-group-news-2-empty))))
 `(gnus-group-news-3 ((t (:bold t :inherit gnus-group-news-3-empty))))
 `(gnus-group-news-4 ((t (:bold t :inherit gnus-group-news-4-empty))))
 `(gnus-group-news-5 ((t (:bold t :inherit gnus-group-news-5-empty))))
 `(gnus-group-news-6 ((t (:bold t :inherit gnus-group-news-6-empty))))
 `(gnus-group-news-low ((t (:bold t :inherit gnus-group-news-low-empty))))
 `(gnus-header-content ((t (:inherit message-header-other))))
 `(gnus-header-from ((t (:inherit message-header-from))))
 `(gnus-header-name ((t (:inherit message-header-name))))
 `(gnus-header-newsgroups ((t (:inherit message-header-other))))
 `(gnus-header-subject ((t (:inherit message-header-subject))))
 `(gnus-summary-cancelled ((t (:foreground ,zenburn-orange))))
 `(gnus-summary-high-ancient ((t (:foreground ,zenburn-blue))))
 `(gnus-summary-high-read ((t (:foreground ,zenburn-green :weight bold))))
 `(gnus-summary-high-ticked ((t (:foreground ,zenburn-orange :weight bold))))
 `(gnus-summary-high-unread ((t (:foreground ,zenburn-fg :weight bold))))
 `(gnus-summary-low-ancient ((t (:foreground ,zenburn-blue))))
 `(gnus-summary-low-read ((t (:foreground ,zenburn-green))))
 `(gnus-summary-low-ticked ((t (:foreground ,zenburn-orange :weight bold))))
 `(gnus-summary-low-unread ((t (:foreground ,zenburn-fg))))
 `(gnus-summary-normal-ancient ((t (:foreground ,zenburn-blue))))
 `(gnus-summary-normal-read ((t (:foreground ,zenburn-green))))
 `(gnus-summary-normal-ticked ((t (:foreground ,zenburn-orange :weight bold))))
 `(gnus-summary-normal-unread ((t (:foreground ,zenburn-fg))))
 `(gnus-summary-selected ((t (:foreground ,zenburn-yellow :weight bold))))
 `(gnus-cite-1 ((t (:foreground ,zenburn-blue))))
 `(gnus-cite-10 ((t (:foreground ,zenburn-yellow-1))))
 `(gnus-cite-11 ((t (:foreground ,zenburn-yellow))))
 `(gnus-cite-2 ((t (:foreground ,zenburn-blue-1))))
 `(gnus-cite-3 ((t (:foreground ,zenburn-blue-2))))
 `(gnus-cite-4 ((t (:foreground ,zenburn-green+2))))
 `(gnus-cite-5 ((t (:foreground ,zenburn-green+1))))
 `(gnus-cite-6 ((t (:foreground ,zenburn-green))))
 `(gnus-cite-7 ((t (:foreground ,zenburn-red))))
 `(gnus-cite-8 ((t (:foreground ,zenburn-red-1))))
 `(gnus-cite-9 ((t (:foreground ,zenburn-red-2))))
 `(gnus-group-news-1-empty ((t (:foreground ,zenburn-yellow))))
 `(gnus-group-news-2-empty ((t (:foreground ,zenburn-green+3))))
 `(gnus-group-news-3-empty ((t (:foreground ,zenburn-green+1))))
 `(gnus-group-news-4-empty ((t (:foreground ,zenburn-blue-2))))
 `(gnus-group-news-5-empty ((t (:foreground ,zenburn-blue-3))))
 `(gnus-group-news-6-empty ((t (:foreground ,zenburn-bg+2))))
 `(gnus-group-news-low-empty ((t (:foreground ,zenburn-bg+2))))
 `(gnus-signature ((t (:foreground ,zenburn-yellow))))
 `(gnus-x ((t (:background ,zenburn-fg :foreground "#3f3f3f"))))
 `(guide-key/highlight-command-face ((t (:foreground ,zenburn-blue))))
 `(guide-key/key-face ((t (:foreground ,zenburn-green))))
 `(guide-key/prefix-command-face ((t (:foreground ,zenburn-green+1))))
 `(helm-header ((t (:foreground ,zenburn-green :background "#3f3f3f" :underline nil :box nil))))
 `(helm-source-header ((t (:foreground ,zenburn-yellow :background ,zenburn-bg-1 :underline nil :weight bold :box (:line-width -1 :style released-button)))))
 `(helm-selection ((t (:background ,zenburn-bg+1 :underline nil))))
 `(helm-selection-line ((t (:background ,zenburn-bg+1))))
 `(helm-visible-mark ((t (:foreground "#3f3f3f" :background ,zenburn-yellow-2))))
 `(helm-candidate-number ((t (:foreground ,zenburn-green+4 :background ,zenburn-bg-1))))
 `(helm-ff-directory ((t (:foreground ,zenburn-magenta))))
 `(hl-line-face ((((class color) (min-colors 89)) (:background "#383838")) (t :weight bold)))
 `(hl-line ((((class color) (min-colors 89)) (:background "#383838")) (t :weight bold)))
 `(hl-sexp-face ((((class color) (min-colors 89)) (:background ,zenburn-bg+1)) (t :weight bold)))
 `(ido-first-match ((t (:foreground ,zenburn-red :weight bold))))
 `(ido-only-match ((t (:foreground ,zenburn-orange :weight bold))))
 `(ido-subdir ((t (:foreground ,zenburn-yellow))))
 `(ido-indicator ((t (:foreground ,zenburn-red :background "#3f3f3f"))))
 `(js2-warning-face ((t (:underline ,zenburn-orange))))
 `(js2-error-face ((t (:foreground ,zenburn-red :weight bold))))
 `(js2-jsdoc-tag-face ((t (:foreground ,zenburn-green-1))))
 `(js2-jsdoc-type-face ((t (:foreground ,zenburn-green+2))))
 `(js2-jsdoc-value-face ((t (:foreground ,zenburn-green+3))))
 `(js2-function-param-face ((t (:foreground ,zenburn-green+3))))
 `(js2-external-variable-face ((t (:foreground ,zenburn-orange))))
 `(js3-warning-face ((t (:underline ,zenburn-yellow))))
 `(js3-error-face ((t (:foreground nil :underline ,zenburn-red))))
 `(js3-external-variable-face ((t (:foreground ,zenburn-magenta))))
 `(js3-function-param-face ((t (:foreground ,zenburn-blue))))
 `(js3-jsdoc-tag-face ((t (:foreground ,zenburn-magenta))))
 `(js3-jsdoc-type-face ((t (:foreground ,zenburn-cyan))))
 `(js3-jsdoc-value-face ((t (:foreground "#6c71c4"))))
 `(js3-jsdoc-html-tag-name-face ((t (:foreground ,zenburn-blue))))
 `(js3-jsdoc-html-tag-delimiter-face ((t (:foreground ,zenburn-green))))
 `(js3-instance-member-face ((t (:foreground ,zenburn-blue))))
 `(js3-private-function-call-face ((t (:foreground ,zenburn-red))))
 `(nxml-name-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-constant-face))))
 `(nxml-attribute-local-name-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-variable-name-face))))
 `(nxml-ref-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-preprocessor-face))))
 `(nxml-delimiter-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-keyword-face))))
 `(nxml-delimited-data-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-string-face))))
 `(rng-error-face ((((class color) (min-colors 89)) (:underline ,zenburn-red))))
 `(erb-delim-face ((((class color) (min-colors 89)) (:background ,zenburn-bg+2))))
 `(erb-exec-face ((((class color) (min-colors 89)) (:background ,zenburn-bg+2 :weight bold))))
 `(erb-exec-delim-face ((((class color) (min-colors 89)) (:background ,zenburn-bg+2))))
 `(erb-out-face ((((class color) (min-colors 89)) (:background ,zenburn-bg+2 :weight bold))))
 `(erb-out-delim-face ((((class color) (min-colors 89)) (:background ,zenburn-bg+2))))
 `(erb-comment-face ((((class color) (min-colors 89)) (:background ,zenburn-bg+2 :weight bold :slant italic))))
 `(erb-comment-delim-face ((((class color) (min-colors 89)) (:background ,zenburn-bg+2))))
 `(jabber-roster-user-away ((t (:foreground ,zenburn-green+2))))
 `(jabber-roster-user-online ((t (:foreground ,zenburn-blue-1))))
 `(jabbee-roster-user-dnd ((t (:foreground ,zenburn-red+1))))
 `(jabber-rare-time-face ((t (:foreground ,zenburn-green+1))))
 `(jabber-chat-prompt-local ((t (:foreground ,zenburn-blue-1))))
 `(jabber-chat-prompt-foreign ((t (:foreground ,zenburn-red+1))))
 `(jabber-activity-face ((t (:foreground ,zenburn-red+1))))
 `(jabber-activity-personal-face ((t (:foreground ,zenburn-blue+1))))
 `(jabber-title-small ((t (:height 1.1 :weight bold))))
 `(jabber-title-medium ((t (:height 1.2 :weight bold))))
 `(jabber-title-large ((t (:height 1.3 :weight bold))))
 `(linum ((t (:foreground ,zenburn-green+2 :background "#3f3f3f"))))
 `(macrostep-gensym-1 ((t (:foreground ,zenburn-green+2 :background ,zenburn-bg-1))))
 `(macrostep-gensym-2 ((t (:foreground ,zenburn-red+1 :background ,zenburn-bg-1))))
 `(macrostep-gensym-3 ((t (:foreground ,zenburn-blue+1 :background ,zenburn-bg-1))))
 `(macrostep-gensym-4 ((t (:foreground ,zenburn-magenta :background ,zenburn-bg-1))))
 `(macrostep-gensym-5 ((t (:foreground ,zenburn-yellow :background ,zenburn-bg-1))))
 `(macrostep-expansion-highlight-face ((t (:inherit highlight))))
 `(macrostep-macro-face ((t (:underline t))))
 `(magit-section-title ((t (:foreground ,zenburn-yellow :weight bold))))
 `(magit-branch ((t (:foreground ,zenburn-orange :weight bold))))
 `(magit-item-highlight ((t (:background ,zenburn-bg+1))))
 `(ediff-current-diff-A ((t (:background "#495766" :foreground ,zenburn-fg))))
 `(ediff-current-diff-Ancestor ((t (:background "#495766" :foreground ,zenburn-fg))))
 `(ediff-current-diff-B ((t (:background "#495766" :foreground ,zenburn-fg))))
 `(ediff-current-diff-C ((t (:background "#495766" :foreground ,zenburn-fg))))

 `(ediff-even-diff-A ((t (:background ,zenburn-bg+1))))
 `(ediff-even-diff-Ancestor ((t (:background ,zenburn-bg+1))))
 `(ediff-even-diff-B ((t (:background ,zenburn-bg+1))))
 `(ediff-even-diff-C ((t (:background ,zenburn-bg+1))))

 `(ediff-odd-diff-A ((t (:background ,zenburn-bg+1))))
 `(ediff-odd-diff-Ancestor ((t (:background ,zenburn-bg+1))))
 `(ediff-odd-diff-B ((t (:background ,zenburn-bg+1))))
 `(ediff-odd-diff-C ((t (:background ,zenburn-bg+1))))

 `(ediff-fine-diff-A ((t (:background "#668b8b"))))
 `(ediff-fine-diff-Ancestor ((t (:background "#668b8b" :foreground ,zenburn-fg))))
 `(ediff-fine-diff-B ((t (:background "#668b8b" :foreground ,zenburn-fg))))
 `(ediff-fine-diff-C ((t (:background "#668b8b" :foreground ,zenburn-fg))))


 `(egg-text-base ((t (:foreground ,zenburn-fg))))
 `(egg-help-header-1 ((t (:foreground ,zenburn-yellow))))
 `(egg-help-header-2 ((t (:foreground ,zenburn-green+3))))
 `(egg-branch ((t (:foreground ,zenburn-yellow))))
 `(egg-branch-mono ((t (:foreground ,zenburn-yellow))))
 `(egg-term ((t (:foreground ,zenburn-yellow))))
 `(egg-diff-add ((t (:foreground ,zenburn-green+4))))
 `(egg-diff-del ((t (:foreground ,zenburn-red+1))))
 `(egg-diff-file-header ((t (:foreground ,zenburn-yellow-2))))
 `(egg-section-title ((t (:foreground ,zenburn-yellow))))
 `(egg-stash-mono ((t (:foreground ,zenburn-green+4))))
 `(message-cited-text ((t (:inherit font-lock-comment))))
 `(message-header-name ((t (:foreground ,zenburn-green+1))))
 `(message-header-other ((t (:foreground ,zenburn-green))))
 `(message-header-to ((t (:foreground ,zenburn-yellow :weight bold))))
 `(message-header-from ((t (:foreground ,zenburn-yellow :weight bold))))
 `(message-header-cc ((t (:foreground ,zenburn-yellow :weight bold))))
 `(message-header-newsgroups ((t (:foreground ,zenburn-yellow :weight bold))))
 `(message-header-subject ((t (:foreground ,zenburn-orange :weight bold))))
 `(message-header-xheader ((t (:foreground ,zenburn-green))))
 `(message-mml ((t (:foreground ,zenburn-yellow :weight bold))))
 `(message-separator ((t (:inherit font-lock-comment))))
 `(mew-face-header-subject ((t (:foreground ,zenburn-orange))))
 `(mew-face-header-from ((t (:foreground ,zenburn-yellow))))
 `(mew-face-header-date ((t (:foreground ,zenburn-green))))
 `(mew-face-header-to ((t (:foreground ,zenburn-red))))
 `(mew-face-header-key ((t (:foreground ,zenburn-green))))
 `(mew-face-header-private ((t (:foreground ,zenburn-green))))
 `(mew-face-header-important ((t (:foreground ,zenburn-blue))))
 `(mew-face-header-marginal ((t (:foreground ,zenburn-fg :weight bold))))
 `(mew-face-header-warning ((t (:foreground ,zenburn-red))))
 `(mew-face-header-xmew ((t (:foreground ,zenburn-green))))
 `(mew-face-header-xmew-bad ((t (:foreground ,zenburn-red))))
 `(mew-face-body-url ((t (:foreground ,zenburn-orange))))
 `(mew-face-body-comment ((t (:foreground ,zenburn-fg :slant italic))))
 `(mew-face-body-cite1 ((t (:foreground ,zenburn-green))))
 `(mew-face-body-cite2 ((t (:foreground ,zenburn-blue))))
 `(mew-face-body-cite3 ((t (:foreground ,zenburn-orange))))
 `(mew-face-body-cite4 ((t (:foreground ,zenburn-yellow))))
 `(mew-face-body-cite5 ((t (:foreground ,zenburn-red))))
 `(mew-face-mark-review ((t (:foreground ,zenburn-blue))))
 `(mew-face-mark-escape ((t (:foreground ,zenburn-green))))
 `(mew-face-mark-delete ((t (:foreground ,zenburn-red))))
 `(mew-face-mark-unlink ((t (:foreground ,zenburn-yellow))))
 `(mew-face-mark-refile ((t (:foreground ,zenburn-green))))
 `(mew-face-mark-unread ((t (:foreground ,zenburn-red-2))))
 `(mew-face-eof-message ((t (:foreground ,zenburn-green))))
 `(mew-face-eof-part ((t (:foreground ,zenburn-yellow))))
 `(paren-face-match ((t (:foreground ,zenburn-cyan :background "#3f3f3f" :weight bold))))
 `(paren-face-mismatch ((t (:foreground "#3f3f3f" :background ,zenburn-magenta :weight bold))))
 `(paren-face-no-match ((t (:foreground "#3f3f3f" :background ,zenburn-red :weight bold))))
 `(mingus-directory-face ((t (:foreground ,zenburn-blue))))
 `(mingus-pausing-face ((t (:foreground ,zenburn-magenta))))
 `(mingus-playing-face ((t (:foreground ,zenburn-cyan))))
 `(mingus-playlist-face ((t (:foreground ,zenburn-cyan))))
 `(mingus-song-file-face ((t (:foreground ,zenburn-yellow))))
 `(mingus-stopped-face ((t (:foreground ,zenburn-red))))
 `(nav-face-heading ((t (:foreground ,zenburn-yellow))))
 `(nav-face-button-num ((t (:foreground ,zenburn-cyan))))
 `(nav-face-dir ((t (:foreground ,zenburn-green))))
 `(nav-face-hdir ((t (:foreground ,zenburn-red))))
 `(nav-face-file ((t (:foreground ,zenburn-fg))))
 `(nav-face-hfile ((t (:foreground ,zenburn-red-4))))
 `(mu4e-cited-1-face ((t (:foreground ,zenburn-blue :slant italic))))
 `(mu4e-cited-2-face ((t (:foreground ,zenburn-green+2 :slant italic))))
 `(mu4e-cited-3-face ((t (:foreground ,zenburn-blue-2 :slant italic))))
 `(mu4e-cited-4-face ((t (:foreground ,zenburn-green :slant italic))))
 `(mu4e-cited-5-face ((t (:foreground ,zenburn-blue-4 :slant italic))))
 `(mu4e-cited-6-face ((t (:foreground ,zenburn-green-1 :slant italic))))
 `(mu4e-cited-7-face ((t (:foreground ,zenburn-blue :slant italic))))
 `(mu4e-replied-face ((t (:foreground "#6f6f6f"))))
 `(mu4e-trashed-face ((t (:foreground "#6f6f6f" :strike-through t))))
 `(mumamo-background-chunk-major ((t (:background nil))))
 `(mumamo-background-chunk-submode1 ((t (:background ,zenburn-bg-1))))
 `(mumamo-background-chunk-submode2 ((t (:background ,zenburn-bg+2))))
 `(mumamo-background-chunk-submode3 ((t (:background "#6f6f6f"))))
 `(mumamo-background-chunk-submode4 ((t (:background ,zenburn-bg+1))))
 `(org-agenda-date-today ((t (:foreground "white" :slant italic :weight bold))))
 `(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 `(org-archived ((t (:foreground ,zenburn-fg :weight bold))))
 `(org-checkbox ((t (:background ,zenburn-bg+2 :foreground "white" :box (:line-width 1 :style released-button)))))
 `(org-date ((t (:foreground ,zenburn-blue :underline t))))
 `(org-deadline-announce ((t (:foreground ,zenburn-red-1))))
 `(org-done ((t (:bold t :weight bold :foreground ,zenburn-green+3))))
 `(org-formula ((t (:foreground ,zenburn-yellow-2))))
 `(org-headline-done ((t (:foreground ,zenburn-green+3))))
 `(org-hide ((t (:foreground ,zenburn-bg-1))))
 `(org-level-1 ((t (:foreground ,zenburn-orange))))
 `(org-level-2 ((t (:foreground ,zenburn-green+4))))
 `(org-level-3 ((t (:foreground ,zenburn-blue-1))))
 `(org-level-4 ((t (:foreground ,zenburn-yellow-2))))
 `(org-level-5 ((t (:foreground ,zenburn-cyan))))
 `(org-level-6 ((t (:foreground ,zenburn-green+2))))
 `(org-level-7 ((t (:foreground ,zenburn-red-4))))
 `(org-level-8 ((t (:foreground ,zenburn-blue-4))))
 `(org-link ((t (:foreground ,zenburn-yellow-2 :underline t))))
 `(org-scheduled ((t (:foreground ,zenburn-green+4))))
 `(org-scheduled-previously ((t (:foreground ,zenburn-red-4))))
 `(org-scheduled-today ((t (:foreground ,zenburn-blue+1))))
 `(org-special-keyword ((t (:foreground "#656555" :weight normal))))
 `(org-table ((t (:foreground ,zenburn-green+2))))
 `(org-tag ((t (:bold t :weight bold))))
 `(org-time-grid ((t (:foreground ,zenburn-orange))))
 `(org-todo ((t (:bold t :foreground ,zenburn-red :weight bold))))
 `(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
 `(org-warning ((t (:bold t :foreground ,zenburn-red :weight bold :underline nil))))
 `(org-column ((t (:background ,zenburn-bg-1))))
 `(org-column-title ((t (:background ,zenburn-bg-1 :underline t :weight bold))))
 `(outline-1 ((t (:foreground ,zenburn-orange))))
 `(outline-2 ((t (:foreground ,zenburn-green+4))))
 `(outline-3 ((t (:foreground ,zenburn-blue-1))))
 `(outline-4 ((t (:foreground ,zenburn-yellow-2))))
 `(outline-5 ((t (:foreground ,zenburn-cyan))))
 `(outline-6 ((t (:foreground ,zenburn-green+2))))
 `(outline-7 ((t (:foreground ,zenburn-red-4))))
 `(outline-8 ((t (:foreground ,zenburn-blue-4))))
 `(rainbow-delimiters-depth-1-face ((t (:foreground ,zenburn-fg))))
 `(rainbow-delimiters-depth-2-face ((t (:foreground ,zenburn-green+2))))
 `(rainbow-delimiters-depth-3-face ((t (:foreground ,zenburn-yellow-2))))
 `(rainbow-delimiters-depth-4-face ((t (:foreground ,zenburn-cyan))))
 `(rainbow-delimiters-depth-5-face ((t (:foreground ,zenburn-green-1))))
 `(rainbow-delimiters-depth-6-face ((t (:foreground ,zenburn-blue+1))))
 `(rainbow-delimiters-depth-7-face ((t (:foreground ,zenburn-yellow-1))))
 `(rainbow-delimiters-depth-8-face ((t (:foreground ,zenburn-green+1))))
 `(rainbow-delimiters-depth-9-face ((t (:foreground ,zenburn-blue-2))))
 `(rainbow-delimiters-depth-10-face ((t (:foreground ,zenburn-orange))))
 `(rainbow-delimiters-depth-11-face ((t (:foreground ,zenburn-green))))
 `(rainbow-delimiters-depth-12-face ((t (:foreground ,zenburn-blue-5))))
 `(mmm-code-submode-face ((t (:background ,zenburn-bg+1))))
 `(mmm-comment-submode-face ((t (:inherit font-lock-comment-face))))
 `(mmm-output-submode-face ((t (:background ,zenburn-bg+1))))
 `(rcirc-my-nick ((t (:foreground ,zenburn-blue))))
 `(rcirc-other-nick ((t (:foreground ,zenburn-orange))))
 `(rcirc-bright-nick ((t (:foreground ,zenburn-blue+1))))
 `(rcirc-dim-nick ((t (:foreground ,zenburn-blue-2))))
 `(rcirc-server ((t (:foreground ,zenburn-green))))
 `(rcirc-server-prefix ((t (:foreground ,zenburn-green+1))))
 `(rcirc-timestamp ((t (:foreground ,zenburn-green+2))))
 `(rcirc-nick-in-message ((t (:foreground ,zenburn-yellow))))
 `(rcirc-nick-in-message-full-line ((t (:bold t))))
 `(rcirc-prompt ((t (:foreground ,zenburn-yellow :bold t))))
 `(rcirc-track-nick ((t (:inverse-video t))))
 `(rcirc-track-keyword ((t (:bold t))))
 `(rcirc-url ((t (:bold t))))
 `(rcirc-keyword ((t (:foreground ,zenburn-yellow :bold t))))
 `(rpm-spec-dir-face ((t (:foreground ,zenburn-green))))
 `(rpm-spec-doc-face ((t (:foreground ,zenburn-green))))
 `(rpm-spec-ghost-face ((t (:foreground ,zenburn-red))))
 `(rpm-spec-macro-face ((t (:foreground ,zenburn-yellow))))
 `(rpm-spec-obsolete-tag-face ((t (:foreground ,zenburn-red))))
 `(rpm-spec-package-face ((t (:foreground ,zenburn-red))))
 `(rpm-spec-section-face ((t (:foreground ,zenburn-yellow))))
 `(rpm-spec-tag-face ((t (:foreground ,zenburn-blue))))
 `(rpm-spec-var-face ((t (:foreground ,zenburn-red))))
 `(rst-level-1-face ((t (:foreground ,zenburn-orange))))
 `(rst-level-2-face ((t (:foreground ,zenburn-green+1))))
 `(rst-level-3-face ((t (:foreground ,zenburn-blue-1))))
 `(rst-level-4-face ((t (:foreground ,zenburn-yellow-2))))
 `(rst-level-5-face ((t (:foreground ,zenburn-cyan))))
 `(rst-level-6-face ((t (:foreground ,zenburn-green-1))))
 `(show-paren-mismatch ((t (:foreground ,zenburn-red-3 :background "#3f3f3f" :weight bold))))
 `(show-paren-match ((t (:foreground ,zenburn-blue-1 :background "#3f3f3f" :weight bold))))
 `(sml-modeline-end-face ((t :inherit default :width condensed)))
 `(slime-repl-inputed-output-face ((t (:foreground ,zenburn-red))))
 `(tabbar-button ((t (:foreground ,zenburn-fg :background "#3f3f3f"))))
 `(tabbar-selected ((t (:foreground ,zenburn-fg :background "#3f3f3f" :box (:line-width -1 :style pressed-button)))))
 `(tabbar-unselected ((t (:foreground ,zenburn-fg :background ,zenburn-bg+1 :box (:line-width -1 :style released-button)))))
 `(term-color-black ((t (:foreground "#3f3f3f" :background ,zenburn-bg-1))))
 `(term-color-red ((t (:foreground ,zenburn-red-2 :background ,zenburn-red-4))))
 `(term-color-green ((t (:foreground ,zenburn-green :background ,zenburn-green+2))))
 `(term-color-yellow ((t (:foreground ,zenburn-orange :background ,zenburn-yellow))))
 `(term-color-blue ((t (:foreground ,zenburn-blue-1 :background ,zenburn-blue-4))))
 `(term-color-magenta ((t (:foreground ,zenburn-magenta :background ,zenburn-red))))
 `(term-color-cyan ((t (:foreground ,zenburn-cyan :background ,zenburn-blue))))
 `(term-color-white ((t (:foreground ,zenburn-fg :background "#656555"))))
 `(term-default-fg-color ((t (:inherit term-color-white))))
 `(term-default-bg-color ((t (:inherit term-color-black))))
 `(vhl/default-face ((t (:background "#383838"))))
 `(w3m-anchor ((t (:foreground ,zenburn-yellow :underline t :weight bold))))
 `(w3m-arrived-anchor ((t (:foreground ,zenburn-yellow-2 :underline t :weight normal))))
 `(w3m-form ((t (:foreground ,zenburn-red-1 :underline t))))
 `(w3m-header-line-location-title ((t (:foreground ,zenburn-yellow :underline t :weight bold))))
 `(w3m-history-current-url ((t (:inherit match))))
 `(w3m-lnum ((t (:foreground ,zenburn-green+2 :background "#3f3f3f"))))
 `(w3m-lnum-match ((t (:background ,zenburn-bg-1 :foreground ,zenburn-orange :weight bold))))
 `(w3m-lnum-minibuffer-prompt ((t (:foreground ,zenburn-yellow))))
 `(whitespace-space ((t (:background ,zenburn-bg+1 :foreground ,zenburn-bg+1))))
 `(whitespace-hspace ((t (:background ,zenburn-bg+1 :foreground ,zenburn-bg+1))))
 `(whitespace-tab ((t (:background ,zenburn-red-1))))
 `(whitespace-newline ((t (:foreground ,zenburn-bg+1))))
 `(whitespace-trailing ((t (:background ,zenburn-red))))
 `(whitespace-line ((t (:background "#3f3f3f" :foreground ,zenburn-magenta))))
 `(whitespace-space-before-tab ((t (:background ,zenburn-orange :foreground ,zenburn-orange))))
 `(whitespace-indentation ((t (:background ,zenburn-yellow :foreground ,zenburn-red))))
 `(whitespace-empty ((t (:background ,zenburn-yellow))))
 `(whitespace-space-after-tab ((t (:background ,zenburn-yellow :foreground
 ,zenburn-red))))
 `(plain-widget-button
   ((t (:weight bold))))
 `(plain-widget-button-pressed
   ((t (:inverse-video t))))
 `(plain-widget-documentation
   ((t (:inherit font-lock-doc))))
 `(plain-widget-field
   ((t (:background ,zenburn-bg+2))))
 `(plain-widget-inactive
   ((t (:strike-through t))))
 `(plain-widget-single-line-field
   ((t (:background ,zenburn-bg+2))))

 `(fancy-widget-button
   ((t (:background ,zenburn-bg+1
                    :box (:line-width 2 :style released-button)))))
 `(fancy-widget-button-pressed
   ((t (:background ,zenburn-bg+1
                    :box (:line-width 2 :style pressed-button)))))
 `(fancy-widget-button-highlight
   ((t (:background ,zenburn-bg+1
                    :box (:line-width 2 :style released-button)))))
 `(fancy-widget-button-pressed-highlight
   ((t (:background ,zenburn-bg+1
                    :box (:line-width 2 :style pressed-button)))))
 `(fancy-widget-documentation
   ((t (:inherit font-lock-doc))))
 `(fancy-widget-field
   ((t (:background ,zenburn-bg+2))))
 `(fancy-widget-inactive
   ((t (:strike-through t))))
 `(fancy-widget-single-line-field
   ((t (:background ,zenburn-bg+2))))

 `(widget-button
   ((t (:inherit plain-widget-button))))
 `(widget-button-pressed
   ((t (:inherit fancy-widget-button-pressed))))
 `(widget-button-highlight
   ((t (:inherit fancy-widget-button-highlight))))
 `(widget-button-pressed-highlight
   ((t (:inherit fancy-widget-button-pressed-highlight))))
 `(widget-documentation
   ((t (:inherit fancy-widget-documentation))))
 `(widget-field
   ((t (:inherit fancy-widget-field))))
 `(widget-inactive
   ((t (:inherit fancy-widget-inactive))))
 `(widget-single-line-field
   ((t (:inherit fancy-widget-single-line-field))))

 `(wl-highlight-folder-few-face ((t (:foreground ,zenburn-red-2))))
 `(wl-highlight-folder-many-face ((t (:foreground ,zenburn-red-1))))
 `(wl-highlight-folder-path-face ((t (:foreground ,zenburn-orange))))
 `(wl-highlight-folder-unread-face ((t (:foreground ,zenburn-blue))))
 `(wl-highlight-folder-zero-face ((t (:foreground ,zenburn-fg))))
 `(wl-highlight-folder-unknown-face ((t (:foreground ,zenburn-blue))))
 `(wl-highlight-message-citation-header ((t (:foreground ,zenburn-red-1))))
 `(wl-highlight-message-cited-text-1 ((t (:foreground ,zenburn-red))))
 `(wl-highlight-message-cited-text-2 ((t (:foreground ,zenburn-green+2))))
 `(wl-highlight-message-cited-text-3 ((t (:foreground ,zenburn-blue))))
 `(wl-highlight-message-cited-text-4 ((t (:foreground ,zenburn-blue+1))))
 `(wl-highlight-message-header-contents-face ((t (:foreground ,zenburn-green))))
 `(wl-highlight-message-headers-face ((t (:foreground ,zenburn-red+1))))
 `(wl-highlight-message-important-header-contents ((t (:foreground ,zenburn-green+2))))
 `(wl-highlight-message-header-contents ((t (:foreground ,zenburn-green+1))))
 `(wl-highlight-message-important-header-contents2 ((t (:foreground ,zenburn-green+2))))
 `(wl-highlight-message-signature ((t (:foreground ,zenburn-green))))
 `(wl-highlight-message-unimportant-header-contents ((t (:foreground ,zenburn-fg))))
 `(wl-highlight-summary-answered-face ((t (:foreground ,zenburn-blue))))
 `(wl-highlight-summary-disposed-face ((t (:foreground ,zenburn-fg :slant italic))))
 `(wl-highlight-summary-new-face ((t (:foreground ,zenburn-blue))))
 `(wl-highlight-summary-normal-face ((t (:foreground ,zenburn-fg))))
 `(wl-highlight-summary-thread-top-face ((t (:foreground ,zenburn-yellow))))
 `(wl-highlight-thread-indent-face ((t (:foreground ,zenburn-magenta))))
 `(wl-highlight-summary-refiled-face ((t (:foreground ,zenburn-fg))))
 `(wl-highlight-summary-displaying-face ((t (:underline t :weight bold))))
 `(which-func ((t (:foreground ,zenburn-green+4))))
 `(yascroll:thumb-text-area ((t (:background ,zenburn-bg-1))))
 `(yascroll:thumb-fringe ((t (:background ,zenburn-bg-1 :foreground ,zenburn-bg-1))))
 `(default ((t (:foreground ,zenburn-fg :background ,zenburn-bg))))

 `(zenburn-background-1 ((t (:background ,zenburn-bg+1))))
 `(zenburn-background-2 ((t (:background ,zenburn-bg+2))))

 `(zenburn-primary-1 ((t (:foreground ,zenburn-yellow :weight bold))))
 `(zenburn-primary-2 ((t (:foreground ,zenburn-orange :weight bold))))
 `(zenburn-primary-3 ((t (:foreground "#dfdfbf" :weight bold))))
 `(zenburn-primary-4 ((t (:foreground ,zenburn-red+1 :weight bold))))
 `(zenburn-primary-5 ((t (:foreground ,zenburn-blue+1 :weight bold))))

 `(zenburn-highlight-damp
   ((t (:foreground "#88b090" :background "#2e3330"))))
 `(zenburn-highlight-alerting
   ((t (:foreground "#e37170" :background "#332323"))))
 `(zenburn-highlight-subtle
   ((t (:background "#464646"))))

 `(zenburn-lowlight-1 ((t (:foreground "#606060"))))
 `(zenburn-lowlight-2 ((t (:foreground "#708070"))))

 `(zenburn-yellow ((t (:foreground ,zenburn-yellow))))
 `(zenburn-orange ((t (:foreground ,zenburn-orange))))
 `(zenburn-red ((t (:foreground ,zenburn-red))))
 `(zenburn-green-1 ((t (:foreground ,zenburn-green-1))))
 `(zenburn-green ((t (:foreground ,zenburn-green))))
 `(zenburn-green+1 ((t (:foreground ,zenburn-green+1))))
 `(zenburn-green+2 ((t (:foreground ,zenburn-green+2))))
 `(zenburn-green+3 ((t (:foreground ,zenburn-green+3))))
 `(zenburn-green+4 ((t (:foreground ,zenburn-green+4))))
 `(zenburn-blue ((t (:foreground ,zenburn-blue))))
 `(zenburn-blue-1 ((t (:foreground ,zenburn-blue-1))))
 `(zenburn-blue-2 ((t (:foreground ,zenburn-blue-2))))
 `(zenburn-blue-3 ((t (:foreground ,zenburn-blue-3))))
 `(zenburn-blue-4 ((t (:foreground ,zenburn-blue-4))))

 `(zenburn-title ((t (:inherit variable-pitch :weight bold))))
)

(provide-theme 'pdc-zenburn)
