(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ack-and-a-half-arguments (quote ("--nopager")))
 '(ack-and-a-half-executable "ack" t)
 '(ack-and-a-half-prompt-for-directory t)
 '(ack-prompt-for-directory t)
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["#3f3f3f" "#cc9393" "#7f9f7f" "#f0dfaf" "#8cd0d3" "#dc8cc3" "#93e0e3" "#dcdccc"])
 '(auto-save-interval 300)
 '(bitly-access-token "7148af4682ed05084192d937d9e9ada306a316bd")
 '(blink-cursor-mode nil)
 '(blink-matching-paren-distance 51200)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(browse-url-browser-function (quote browse-url-default-browser))
 '(browse-url-generic-program "google-chrome")
 '(buffers-menu-show-directories (quote unless-uniquify))
 '(coffee-command "/usr/local/share/npm/bin/coffee")
 '(coffee-tab-width 4)
 '(column-number-mode t)
 '(comint-buffer-maximum-size 20000)
 '(comint-input-ignoredups t)
 '(comint-input-ring-size 5000)
 '(comint-prompt-read-only t)
 '(comint-scroll-to-bottom-on-input t)
 '(compilation-error-screen-columns nil)
 '(completion-category-overrides (quote ((buffer (styles basic substring initials)))))
 '(completion-styles (quote (basic partial-completion initials emacs22)))
 '(confluence-save-credentials t)
 '(confluence-url "https://confluence.ntt.eu/rpc/xmlrpc")
 '(cperl-auto-newline nil)
 '(cperl-close-paren-offset -4)
 '(cperl-continued-statement-offset 4)
 '(cperl-fix-hanging-brace-when-indent nil)
 '(cperl-indent-level 4)
 '(cperl-indent-parens-as-block t)
 '(cperl-indent-subs-specially nil)
 '(cperl-label-offset -4)
 '(cperl-merge-trailing-else nil)
 '(cperl-tab-always-indent t)
 '(cua-enable-cua-keys nil)
 '(cua-keep-region-after-copy t)
 '(cua-remap-control-v nil)
 '(current-language-environment "English")
 '(cursor-type (quote bar))
 '(custom-enabled-themes (quote (zenburn)))
 '(custom-safe-themes
   (quote
    ("0c01de11a478d411fcbd5c16e4757900dc34b1d859d46ab320d4b4452765923d" "c0d743b59ef10a9d8f21a6b0447ed729f1ff7136b14968f2f76a7e1bb9600366" "58ede9ae92e608cc051fa7c64cd648405b77cee62970e3ae55179e0e5486240a" default)))
 '(default-fill-column 78 t)
 '(default-frame-alist
    (quote
     ((top . 50)
      (left . 100)
      (width . 110)
      (height . 40)
      (cursor-color . "#dcdccc"))))
 '(default-input-method nil)
 '(default-mime-charset (quote utf-8))
 '(delete-selection-mode t nil (delsel))
 '(dictionary-default-popup-strategy "soundex")
 '(diff-switches "-u")
 '(dired-use-ls-dired nil)
 '(display-buffer-reuse-frames nil)
 '(ecb-options-version "2.33beta1")
 '(enable-recursive-minibuffers t)
 '(enable-remote-dir-locals t)
 '(eval-expression-print-length nil)
 '(eval-expression-print-level nil)
 '(ewd-kp-usage (quote num))
 '(fci-rule-color "#383838")
 '(fill-column 78)
 '(font-lock-support-mode (quote jit-lock-mode))
 '(footnote-section-tag-regexp "Footnotes\\(\\[.\\]\\)?: *")
 '(footnote-use-message-mode nil)
 '(frame-background-mode (quote light))
 '(geiser-guile-binary "/usr/local/bin/guile")
 '(geiser-racket-binary "/Applications/Racket/bin/racket")
 '(global-auto-revert-mode t)
 '(global-mark-ring-max 60)
 '(global-whitespace-mode nil)
 '(gnus-default-nntp-server "news.merula.co.uk")
 '(gnus-novice-user nil)
 '(grep-command "grep -n -e")
 '(haskell-program-name "ghci")
 '(hippie-expand-try-functions-list
   (quote
    (try-complete-abbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill)))
 '(history-delete-duplicates t)
 '(icomplete-mode nil)
 '(indent-region-mode t t)
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote right))
 '(indicate-empty-lines t)
 '(inferior-lisp-program "/usr/local/bin/openmcl -K utf-8" t)
 '(initial-major-mode (quote lisp-interaction-mode))
 '(ispell-extra-args (quote ("--sug-mode=ultra")))
 '(ispell-program-name "/usr/local/bin/aspell")
 '(ispell-silently-savep t)
 '(iswitchb-default-method (quote samewindow))
 '(javascript-indent-level 2)
 '(js2-auto-indent-flag nil)
 '(js2-indent-on-enter-key nil)
 '(js2-language-version 150)
 '(js2-missing-semi-one-line-override t)
 '(js2-strict-inconsistent-return-warning nil)
 '(less-css-compile-at-save nil)
 '(mac-emulate-three-button-mouse nil t)
 '(mac-inline-input-method-mode nil t)
 '(mac-key-mode t)
 '(mac-key-mode-hook nil)
 '(mac-wheel-button-is-mouse-2 t t)
 '(magit-git-executable "/u/virtual/pdc/bin/git")
 '(max-specpdl-size 10000)
 '(mediawiki-site-alist
   (quote
    (("Wikipedia" "http://en.wikipedia.org/w/" "username" "password" "Main Page")
     ("ThermeonWiki" "https://wiki.thermeon.eu/" "" "" ""))))
 '(message-send-mail-function (quote smtpmail-send-it))
 '(minibuffer-eldef-shorten-default t)
 '(mode-require-final-newline (quote visit-save))
 '(mouse-region-delete-keys (quote ([delete] [deletechar] [backspace])))
 '(next-line-add-newlines nil)
 '(next-screen-context-lines 1)
 '(ns-alternate-modifier (quote meta))
 '(ns-command-modifier (quote super))
 '(ns-function-modifier (quote alt))
 '(ns-pop-up-frames nil)
 '(ns-right-alternate-modifier (quote alt))
 '(ns-use-native-fullscreen nil)
 '(ns-use-qd-smoothing nil)
 '(ns-use-system-highlight-color nil t)
 '(nxml-bind-meta-tab-to-complete-flag t)
 '(nxml-slash-auto-complete-flag t)
 '(org-agenda-files
   (quote
    ("~/Dropbox/org/codex.org" "~/Dropbox/org/blog.org" "~/Dropbox/org/todo.org" "~/Dropbox/org/technology.org" "~/Dropbox/org/journal.org")))
 '(org-default-notes-file "codex.org")
 '(org-directory "~/Dropbox/org")
 '(org-html-doctype "html5")
 '(org-html-html5-fancy t)
 '(org-html-indent nil)
 '(org-mobile-inbox-for-pull "~/Dropbox/org/from-mobile.org")
 '(org-modules
   (quote
    (org-bbdb org-bibtex org-docview org-gnus org-id org-info org-protocol org-eshell org-habit org-inlinetask org-irc org-mhe org-protocol org-rmail org-w3m org-mouse org-mac-iCal org-timer)))
 '(org-protocol-default-template-key "w")
 '(org-startup-indented t)
 '(org-timer-default-timer 25)
 '(org-todo-keywords
   (quote
    ((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!/!)" "WONTFIX(W@/!)")
     (sequence "WAITING(w@/!)" "SOMEDAY(s!)" "|" "CANCELLED(c@/!)")
     (sequence "OPEN(O)" "|" "CLOSED(C)"))))
 '(overflow-newline-into-fringe t)
 '(package-selected-packages
   (quote
    (ack fm git-gutter-fringe+ whitespace-cleanup-mo tagedit ssh-config project-mode project-buffer-mode pbcopy org-mode org-magit nterm mo-git-blame lineker filladapt emacs-jabber desktop-recover breadcrumb auto-complete-extension auto-complete-etags asciidoc ack-and-a-half yasnippet-snippets yasnippets lispy avy git-gutter+ counsel flycheck elixir-mode go-mode rainbow-mode project-local-variables)))
 '(pc-selection-mode nil)
 '(pdc/mc-cmds
   (quote
    (forward-sexp backward-sexp cperl-electric-semi cperl-electric-brace cperl-electric-lbrace cperl-electric-backspace cperl-electric-paren cperl-electric-rparen)))
 '(rails-always-use-text-menus t)
 '(read-mail-command (quote gnus))
 '(require-final-newline t)
 '(safe-local-variable-values
   (quote
    ((eval font-lock-add-keywords nil
           (quote
            (("defexamples\\|def-example-group\\| => "
              (0
               (quote font-lock-keyword-face))))))
     (standard-indent . 2)
     (hc-highlight-other-chars-p)
     (hc-highlight-hard-hyphens-p)
     (hc-highlight-hard-spaces-p)
     (hc-highlight-trailing-whitespace-p)
     (hc-highlight-tabs-p)
     (whitespace-style face tabs spaces trailing lines space-before-tab::space newline indentation::space empty space-after-tab::space space-mark tab-mark newline-mark)
     (eval ignore-errors "Write-contents-functions is a buffer-local alternative to before-save-hook"
           (add-hook
            (quote write-contents-functions)
            (lambda nil
              (delete-trailing-whitespace)
              nil))
           (require
            (quote whitespace))
           "Sometimes the mode needs to be toggled off and on."
           (whitespace-mode 0)
           (whitespace-mode 1))
     (whitespace-line-column . 80)
     (whitespace-style face tabs trailing lines-tail)
     (magit-git-executable . "/home/staff/pdc/git/bin/git")
     (cperl-close-paren-offset . -1)
     (cperl-brace-imaginary-offset . 0)
     (cperl-tab-always-indent . t)
     (cperl-indent-parens-as-block . t)
     (cperl-fix-hanging-brace-when-indent)
     (cperl-close-paren-offset . 0)
     (cperl-brace-imaginary-offset . 4)
     (cperl-auto-newline)
     (ack-and-a-half-executable . "/home/staff/pdc/bin/ack")
     (ffap-perl-module-path "/scpc:grebe:/home/piers.cawley/Projects/nexus/lib/perl" "/scpc:grebe:/home/piers.cawley/Projects/nexus/gui/nboss-customer-portal" "/scpc:grebe:/home/piers.cawley/Projects/nexus/gui/customer-portal" "/scpc:grebe:/home/piers.cawley/Projects/nexus/gui/partner-portal" "/scpc:grebe:/home/piers.cawley/Projects/nexus/gui/sir")
     (ffap-perl-module-path mapcar
                            (function expand-path)
                            ("lib/perl" "gui/nboss-customer-portal" "gui/customer-portal" "gui/partner-portal" "gui/sir"))
     (ffap-perl-module-path "lib/perl" "gui/nboss-customer-portal" "gui/customer-portal" "gui/partner-portal" "gui/sir"))))
 '(scroll-conservatively 0)
 '(scroll-preserve-screen-position t)
 '(scroll-step 0)
 '(server-mode t)
 '(session-use-package t nil (session))
 '(shell-prompt-pattern "^[^$>
]*[#$%>] *\\([[0-9;]*[a-zA-Z] *\\)*")
 '(show-paren-style (quote parenthesis))
 '(slime-autodoc-use-multiline-p t)
 '(slime-complete-symbol*-fancy t)
 '(slime-complete-symbol-function (quote slime-complete-symbol*))
 '(starttls-gnutls-program "/usr/local/bin/gnutls-cli")
 '(tab-width 4)
 '(temp-buffer-max-height (lambda (buffer) (/ (- (frame-height) 2) 3)))
 '(temp-buffer-resize-mode nil)
 '(text-mode-hook (quote (text-mode-hook-identify pdc/turn-on-abbrev-mode)))
 '(tls-checktrust (quote ask))
 '(tls-program
   (quote
    ("/usr/local/bin/gnutls-cli --insecure -p %p %h" "/usr/local/bin/gnutls-cli --insecure -p %p %h --protocols ssl3" "/usr/bin/openssl s_client -connect %h:%p -no_ssl2 -ign_eof")))
 '(tool-bar-mode nil)
 '(tramp-verbose 4)
 '(uniquify-buffer-name-style (quote post-forward-angle-brackets) nil (uniquify))
 '(uniquify-ignore-buffers-re "^\\*")
 '(uniquify-separator ":")
 '(vc-annotate-background "#2b2b2b")
 '(vc-annotate-color-map
   (quote
    ((20 . "#bc8383")
     (40 . "#cc9393")
     (60 . "#dfaf8f")
     (80 . "#d0bf8f")
     (100 . "#e0cf9f")
     (120 . "#f0dfaf")
     (140 . "#5f7f5f")
     (160 . "#7f9f7f")
     (180 . "#8fb28f")
     (200 . "#9fc59f")
     (220 . "#afd8af")
     (240 . "#bfebbf")
     (260 . "#93e0e3")
     (280 . "#6ca0a3")
     (300 . "#7cb8bb")
     (320 . "#8cd0d3")
     (340 . "#94bff3")
     (360 . "#dc8cc3"))))
 '(vc-annotate-very-old-color "#dc8cc3")
 '(visible-bell nil)
 '(visual-scroll-margin nil)
 '(w3m-command "/opt/local/bin/w3m" t)
 '(w3m-use-cookies t)
 '(wdired-allow-to-change-permissions (quote advanced))
 '(web-mode-attr-indent-offset 2)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-auto-expanding t)
 '(web-mode-indent-style 2)
 '(web-mode-markup-indent-offset 2)
 '(wg-mode-line-on nil)
 '(whitespace-action (quote (auto-cleanup)))
 '(whitespace-line-column nil)
 '(whitespace-style (quote (tabs trailing space-before-tab)))
 '(woman-use-own-frame nil)
 '(xterm-mouse-mode t))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aquamacs-variable-width ((t (:height 140 :family "Lucida Grande"))) t)
 '(hc-tab ((t (:inherit whitespace-tab))))
 '(web-mode-html-tag-bracket-face ((t (:inherit zenburn-green-4)))))
