(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(auto-save-interval 300)
 '(blink-matching-paren-distance 51200)
 '(compilation-error-screen-columns nil)
 '(current-language-environment "English")
 '(default-fill-column 77 t)
 '(default-frame-alist (quote ((top . 50) (left . 100) (width . 110) (height . 40) (cursor-color . "#dcdccc"))))
 '(default-input-method nil)
 '(default-mime-charset (quote utf-8))
 '(delete-selection-mode nil nil (delsel))
 '(dictionary-default-popup-strategy "soundex")
 '(ecb-options-version "2.33beta1")
 '(ewd-kp-usage (quote num))
 '(exec-path (cons "~/bin" exec-path))
 '(fill-column 79)
 '(font-lock-support-mode (quote jit-lock-mode))
 '(footnote-section-tag-regexp "Footnotes\\(\\[.\\]\\)?: *")
 '(footnote-use-message-mode nil)
 '(frame-background-mode (quote light))
 '(global-auto-revert-mode t)
 '(global-font-lock-mode t nil (font-lock))
 '(grep-command "grep -n -e")
 '(hippie-expand-try-functions-list (quote (try-complete-abbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill)))
 '(ido-auto-merge-work-directories-length -1)
 '(ido-case-fold t)
 '(ido-default-buffer-method (quote selected-window))
 '(ido-default-file-method (quote selected-window))
 '(ido-everywhere t)
 '(ido-mode (quote both) nil (ido))
 '(ido-show-dot-for-dired nil)
 '(ido-use-filename-at-point nil)
 '(indent-region-mode t)
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote right))
 '(indicate-empty-lines t)
 '(inferior-lisp-program "/usr/local/bin/openmcl -K utf-8")
 '(ispell-program-name "/opt/local/bin/aspell")
 '(iswitchb-default-method (quote samewindow))
 '(javascript-indent-level 2)
 '(js2-auto-indent-flag nil)
 '(js2-indent-on-enter-key nil)
 '(js2-language-version 150)
 '(js2-missing-semi-one-line-override t)
 '(js2-strict-inconsistent-return-warning nil)
 '(mac-emulate-three-button-mouse nil)
 '(mac-key-mode t)
 '(mac-key-mode-hook nil)
 '(mac-wheel-button-is-mouse-2 t)
 '(mmm-global-mode (quote maybe) nil (mmm-mode))
 '(mmm-submode-decoration-level 2)
 '(mode-require-final-newline (quote visit-save))
 '(next-line-add-newlines nil)
 '(next-screen-context-lines 1)
 '(ns-alternate-modifier (quote meta) t)
 '(ns-command-modifier (quote alt) t)
 '(nxhtml-default-encoding (quote utf-8))
 '(nxhtml-global-minor-mode t)
 '(nxhtml-global-validation-header-mode t)
 '(nxhtml-skip-welcome t)
 '(nxml-attribute-indent 2)
 '(nxml-slash-auto-complete-flag t)
 '(overflow-newline-into-fringe t)
 '(rails-always-use-text-menus t)
 '(require-final-newline (quote visit-save))
 '(scroll-preserve-screen-position t)
 '(show-paren-mode t)
 '(show-paren-style (quote parenthesis))
 '(slime-autodoc-use-multiline-p t)
 '(slime-complete-symbol*-fancy t)
 '(slime-complete-symbol-function (quote slime-complete-symbol*))
 '(tab-width 4)
 '(temp-buffer-max-height (lambda (buffer) (/ (- (frame-height) 2) 3)))
 '(temp-buffer-resize-mode nil)
 '(text-mode-hook (quote (turn-on-auto-fill text-mode-hook-identify)))
 '(transient-mark-mode t)
 '(visible-bell nil)
 '(woman-use-own-frame nil))

(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
)
