(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ack-and-a-half-arguments (quote ("--nopager")))
 '(ack-and-a-half-executable "/u/virtual/pdc/bin/ack" t)
 '(ack-and-a-half-prompt-for-directory t)
 '(ack-prompt-for-directory t)
 '(ansi-color-names-vector
   ["#3f3f3f" "#cc9393" "#7f9f7f" "#f0dfaf" "#8cd0d3" "#dc8cc3" "#93e0e3" "#dcdccc"])
 '(auto-save-interval 300)
 '(bitly-access-token "7148af4682ed05084192d937d9e9ada306a316bd")
 '(blink-cursor-mode nil)
 '(blink-matching-paren-distance 51200)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(browse-url-browser-function (quote browse-url-default-browser))
 '(browse-url-generic-program "google-chrome")
 '(buffers-menu-show-directories (quote unless-uniquify))
 '(coffee-command "/usr/local/share/npm/bin/coffee")
 '(coffee-tab-width 4)
 '(column-number-mode t)
 '(comint-buffer-maximum-size 20000)
 '(comint-input-ignoredups t)
 '(comint-input-ring-size 5000)
 '(comint-prompt-read-only t)
 '(comint-scroll-to-bottom-on-input t)
 '(compilation-error-screen-columns nil)
 '(completion-category-overrides (quote ((buffer (styles basic substring initials)))))
 '(completion-styles (quote (basic partial-completion initials emacs22)))
 '(confluence-save-credentials t)
 '(confluence-url "https://confluence.ntt.eu/rpc/xmlrpc")
 '(cperl-auto-newline nil)
 '(cperl-close-paren-offset -4)
 '(cperl-continued-statement-offset 4)
 '(cperl-fix-hanging-brace-when-indent nil)
 '(cperl-indent-level 4)
 '(cperl-indent-parens-as-block t)
 '(cperl-indent-subs-specially nil)
 '(cperl-label-offset -4)
 '(cperl-merge-trailing-else nil)
 '(cperl-tab-always-indent t)
 '(cua-enable-cua-keys nil)
 '(cua-keep-region-after-copy t)
 '(cua-remap-control-v nil)
 '(current-language-environment "English")
 '(cursor-type (quote bar))
 '(custom-enabled-themes (quote (pdc-zenburn)))
 '(custom-safe-themes
   (quote
    ("f72c55281f894898c88fba03d84e0a8d64b4c7039e4249da91cf0f4577ba1124" "0261d8aca24a5b0e1f9138c49c758a9c7215b60736c7f51b130f81d7aed03884" "35290fcff26737b6f0d7674deebc6701e43f2e281ce73a235c9d08e9630a4a5c" "8fc9387bf6302020929ba8f8524cd92d6825bfb2e76f09a19fe59f6cc435b773" "66bd972acaaffbe24ac94c6a81e71c33d7ff87746c5e08c51920005a8113fe53" "92f744d9a97bb8f99565fade6bf093787466e22e6d1be4b0cf68e07c73f93f19" "5359fb73898840ada2ae5d69877f2d817a1672185013049955672fc6438a4bd4" "83cffe882af5fdb996897f17b68cf2b309ca618afc0fba0eae3884bfee890429" "2a954a51b071b4e63d62acf6381f2ddbea9a528c94360d797f82319a78a2c57b" "4c9ba94db23a0a3dea88ee80f41d9478c151b07cb6640b33bfc38be7c2415cc4" default)))
 '(default-fill-column 78 t)
 '(default-frame-alist
    (quote
     ((top . 50)
      (left . 100)
      (width . 110)
      (height . 40)
      (cursor-color . "#dcdccc"))))
 '(default-input-method nil)
 '(default-mime-charset (quote utf-8))
 '(delete-selection-mode t nil (delsel))
 '(dictionary-default-popup-strategy "soundex")
 '(diff-switches "-u")
 '(dired-use-ls-dired nil)
 '(display-buffer-reuse-frames nil)
 '(ecb-options-version "2.33beta1")
 '(enable-recursive-minibuffers t)
 '(enable-remote-dir-locals t)
 '(eval-expression-print-length nil)
 '(eval-expression-print-level nil)
 '(ewd-kp-usage (quote num))
 '(fci-rule-color "#383838")
 '(fill-column 78)
 '(font-lock-support-mode (quote jit-lock-mode))
 '(footnote-section-tag-regexp "Footnotes\\(\\[.\\]\\)?: *")
 '(footnote-use-message-mode nil)
 '(frame-background-mode (quote light))
 '(geiser-guile-binary "/usr/local/bin/guile")
 '(geiser-racket-binary "/Applications/Racket/bin/racket")
 '(global-auto-revert-mode t)
 '(global-mark-ring-max 60)
 '(global-whitespace-mode nil)
 '(gnus-default-nntp-server "news.merula.co.uk")
 '(gnus-novice-user nil)
 '(grep-command "grep -n -e")
 '(haskell-program-name "ghci")
 '(hippie-expand-try-functions-list
   (quote
    (try-complete-abbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill)))
 '(history-delete-duplicates t)
 '(icomplete-mode nil)
 '(indent-region-mode t t)
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote right))
 '(indicate-empty-lines t)
 '(inferior-lisp-program "/usr/local/bin/openmcl -K utf-8" t)
 '(initial-major-mode (quote lisp-interaction-mode))
 '(ispell-extra-args (quote ("--sug-mode=ultra")))
 '(ispell-program-name "/usr/local/bin/aspell")
 '(ispell-silently-savep t)
 '(iswitchb-default-method (quote samewindow))
 '(javascript-indent-level 2)
 '(js2-auto-indent-flag nil)
 '(js2-indent-on-enter-key nil)
 '(js2-language-version 150)
 '(js2-missing-semi-one-line-override t)
 '(js2-strict-inconsistent-return-warning nil)
 '(less-css-compile-at-save nil)
 '(mac-emulate-three-button-mouse nil t)
 '(mac-inline-input-method-mode nil t)
 '(mac-key-mode t)
 '(mac-key-mode-hook nil)
 '(mac-wheel-button-is-mouse-2 t t)
 '(magit-git-executable "/u/virtual/pdc/bin/git")
 '(max-specpdl-size 10000)
 '(mediawiki-site-alist
   (quote
    (("Wikipedia" "http://en.wikipedia.org/w/" "username" "password" "Main Page")
     ("ThermeonWiki" "https://wiki.thermeon.eu/" "" "" ""))))
 '(message-send-mail-function (quote smtpmail-send-it))
 '(minibuffer-eldef-shorten-default t)
 '(mode-require-final-newline (quote visit-save))
 '(mouse-region-delete-keys (quote ([delete] [deletechar] [backspace])))
 '(next-line-add-newlines nil)
 '(next-screen-context-lines 1)
 '(ns-alternate-modifier (quote meta))
 '(ns-command-modifier (quote super))
 '(ns-function-modifier (quote alt))
 '(ns-pop-up-frames nil)
 '(ns-right-alternate-modifier (quote alt))
 '(ns-use-native-fullscreen nil)
 '(ns-use-qd-smoothing nil)
 '(ns-use-system-highlight-color nil t)
 '(nxml-bind-meta-tab-to-complete-flag t)
 '(nxml-slash-auto-complete-flag t)
 '(org-agenda-files
   (quote
    ("~/Dropbox/org/codex.org" "~/Dropbox/org/blog.org" "~/Dropbox/org/todo.org" "~/Dropbox/org/technology.org" "~/Dropbox/org/journal.org")))
 '(org-default-notes-file "codex.org")
 '(org-directory "~/Dropbox/org")
 '(org-html-doctype "html5")
 '(org-html-html5-fancy t)
 '(org-html-indent nil)
 '(org-mobile-inbox-for-pull "~/Dropbox/org/from-mobile.org")
 '(org-modules
   (quote
    (org-bbdb org-bibtex org-docview org-gnus org-id org-info org-protocol org-eshell org-habit org-inlinetask org-irc org-mhe org-protocol org-rmail org-w3m org-mouse org-mac-iCal org-timer)))
 '(org-protocol-default-template-key "w")
 '(org-startup-indented t)
 '(org-timer-default-timer 25)
 '(org-todo-keywords
   (quote
    ((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!/!)" "WONTFIX(W@/!)")
     (sequence "WAITING(w@/!)" "SOMEDAY(s!)" "|" "CANCELLED(c@/!)")
     (sequence "OPEN(O)" "|" "CLOSED(C)"))))
 '(overflow-newline-into-fringe t)
 '(package-selected-packages
   (quote
    (ocodo-svg-modelines racket-mode znc zencoding-mode yaml-mode yagist xcscope workgroups winpoint window-numbering whole-line-or-region whitespace-cleanup-mode wgrep websocket web-mode visual-regexp-steroids visible-mark virtualenv use-package unipoint unicode-enbox unfill unbound ucs-cmds typing tt-mode time-ext thingatpt+ thing-cmds textmate-to-yas textile-mode tex-math-preview tagedit syslog-mode sws-mode swift-mode sunrise-x-modeline sunrise-x-checkpoints string-inflection ssh-config-mode ssh spaces smex smart-compile slime-js session scss-mode scratch-palette save-packages sauron sackspace s-buffer runner reveal-in-finder restclient requirejs-mode request regex-tool rect+ rainbow-mode rainbow-delimiters project-persist project-mode project-local-variables project pretty-mode powerline popup-kill-ring perlbrew pcre2el pcmpl-args pbcopy pastebin packed package ox-textile ox-reveal ox-html5slide ox-asciidoc osx-pseudo-daemon osx-plist osx-location osx-clipboard osx-browse org2blog org-screenshot org-repo-todo org-protocol-jekyll org-present org-pandoc org-mobile-sync org-magit org-mac-link org-mac-iCal org-journal org-jekyll org-elisp-help org-drill-table org-context org-bullets org-blog org-agenda-property openwith objc-font-lock ob-translate ob-sml ob-browser oauth2 o-blog nzenburn-theme nterm nrepl nginx-mode nav multi-term moz monky mo-git-blame mmm-mode melpa-upstream-visit mediawiki mc-extras mb-depth+ math-symbols markdown-mode+ mark-tools mark-multiple map-regexp magit-gitflow magit-gh-pulls magit-find-file macrostep macro-utils lusty-explorer loop log4j-mode load-dir list-register lexbind-mode lcs latex-preview-pane latex-pretty-symbols lang-refactor-perl keywiz keymap-utils keyfreq json-mode js3-mode js2-refactor js-comint jquery-doc jenkins-watch itail isend-mode isearch+ ipython instapaper info+ inflections iflipb iedit ido-vertical-mode ido-ubiquitous ido-hacks ido-gnus ido-complete-space-or-hyphen idle-highlight-mode ibuffer-vc httpcode http-twiddle htmlize ht howdoi highlight-symbol highlight-cl highlight-chars hi2 handlebars-mode haml-mode ham-mode gtags graphviz-dot-mode goto-last-change gotest golint go-snippets go-projectile go-play go-errcheck go-direx go-autocomplete gntp gitty gitignore-mode gitconfig-mode gitconfig git-gutter-fringe git-gutter-fringe+ git-blame git gist ghci-completion ghc geiser foreign-regexp fm flymake-yaml flymake-shell flymake-sass flymake-ruby flymake-perlcritic flymake-less flymake-json flymake-hlint flymake-haskell-multi flymake-haml flymake-go flymake-coffee flycheck-tip flycheck-hdevtools flycheck-haskell flycheck-color-mode-line flx-ido fliptext find-file-in-repository feature-mode fastnav express expand-region exec-path-from-shell evil-surround evil-paredit evil-numbers evil-nerd-commenter evil-leader etags-select ess erlang erefactor emr emamux elnode elixir-yasnippets elixir-mode elixir-mix elisp-slime-nav elein electric-case eldoc-extension el-autoyas edebug-x ebib dropbox dot-mode dockerfile-mode discover dired-efap dired-dups dired-details+ dired+ diff-hl diff-git dict-tree deft dedicated db-pg dash-functional dash-at-point cus-edit+ cursor-chg csv-nav csv-mode command-t combinators color-theme color-moccur coffee-mode clojure-test-mode cdlatex cache butler bufshow buffer-move browse-kill-ring bookmark+ bm bibslurp bibretrieve bang backtrace-mode autopair auto-yasnippet auto-complete-etags auto-async-byte-compile auctex-latexmk asciidoc applescript-mode apache-mode anything ansi align-cljlet adoc-mode ack-menu ack-and-a-half ace-jump-mode ac-slime ac-nrepl ac-math ac-js2 ac-dabbrev abc-mode 2048-game)))
 '(pc-selection-mode nil)
 '(pdc/mc-cmds
   (quote
    (forward-sexp backward-sexp cperl-electric-semi cperl-electric-brace cperl-electric-lbrace cperl-electric-backspace cperl-electric-paren cperl-electric-rparen)))
 '(rails-always-use-text-menus t)
 '(read-mail-command (quote gnus))
 '(require-final-newline t)
 '(safe-local-variable-values
   (quote
    ((eval ignore-errors "Write-contents-functions is a buffer-local alternative to before-save-hook"
           (add-hook
            (quote write-contents-functions)
            (lambda nil
              (delete-trailing-whitespace)
              nil))
           (require
            (quote whitespace))
           "Sometimes the mode needs to be toggled off and on."
           (whitespace-mode 0)
           (whitespace-mode 1))
     (whitespace-line-column . 80)
     (whitespace-style face tabs trailing lines-tail)
     (magit-git-executable . "/home/staff/pdc/git/bin/git")
     (cperl-close-paren-offset . -1)
     (cperl-brace-imaginary-offset . 0)
     (cperl-tab-always-indent . t)
     (cperl-indent-parens-as-block . t)
     (cperl-fix-hanging-brace-when-indent)
     (cperl-close-paren-offset . 0)
     (cperl-brace-imaginary-offset . 4)
     (cperl-auto-newline)
     (ack-and-a-half-executable . "/home/staff/pdc/bin/ack")
     (ffap-perl-module-path "/scpc:grebe:/home/piers.cawley/Projects/nexus/lib/perl" "/scpc:grebe:/home/piers.cawley/Projects/nexus/gui/nboss-customer-portal" "/scpc:grebe:/home/piers.cawley/Projects/nexus/gui/customer-portal" "/scpc:grebe:/home/piers.cawley/Projects/nexus/gui/partner-portal" "/scpc:grebe:/home/piers.cawley/Projects/nexus/gui/sir")
     (ffap-perl-module-path mapcar
                            (function expand-path)
                            ("lib/perl" "gui/nboss-customer-portal" "gui/customer-portal" "gui/partner-portal" "gui/sir"))
     (ffap-perl-module-path "lib/perl" "gui/nboss-customer-portal" "gui/customer-portal" "gui/partner-portal" "gui/sir"))))
 '(scroll-conservatively 0)
 '(scroll-preserve-screen-position t)
 '(scroll-step 0)
 '(server-mode t)
 '(session-use-package t nil (session))
 '(shell-prompt-pattern "^[^$>
]*[#$%>] *\\([[0-9;]*[a-zA-Z] *\\)*")
 '(show-paren-style (quote parenthesis))
 '(slime-autodoc-use-multiline-p t)
 '(slime-complete-symbol*-fancy t)
 '(slime-complete-symbol-function (quote slime-complete-symbol*))
 '(starttls-gnutls-program "/usr/local/bin/gnutls-cli")
 '(tab-width 4)
 '(temp-buffer-max-height (lambda (buffer) (/ (- (frame-height) 2) 3)))
 '(temp-buffer-resize-mode nil)
 '(text-mode-hook (quote (text-mode-hook-identify pdc/turn-on-abbrev-mode)))
 '(tls-checktrust (quote ask))
 '(tls-program
   (quote
    ("/usr/local/bin/gnutls-cli --insecure -p %p %h" "/usr/local/bin/gnutls-cli --insecure -p %p %h --protocols ssl3" "/usr/bin/openssl s_client -connect %h:%p -no_ssl2 -ign_eof")))
 '(tool-bar-mode nil)
 '(tramp-verbose 4)
 '(uniquify-buffer-name-style (quote post-forward-angle-brackets) nil (uniquify))
 '(uniquify-ignore-buffers-re "^\\*")
 '(uniquify-separator ":")
 '(vc-annotate-background "#2b2b2b")
 '(vc-annotate-color-map
   (quote
    ((20 . "#bc8383")
     (40 . "#cc9393")
     (60 . "#dfaf8f")
     (80 . "#d0bf8f")
     (100 . "#e0cf9f")
     (120 . "#f0dfaf")
     (140 . "#5f7f5f")
     (160 . "#7f9f7f")
     (180 . "#8fb28f")
     (200 . "#9fc59f")
     (220 . "#afd8af")
     (240 . "#bfebbf")
     (260 . "#93e0e3")
     (280 . "#6ca0a3")
     (300 . "#7cb8bb")
     (320 . "#8cd0d3")
     (340 . "#94bff3")
     (360 . "#dc8cc3"))))
 '(vc-annotate-very-old-color "#dc8cc3")
 '(visible-bell nil)
 '(visual-scroll-margin nil)
 '(w3m-command "/opt/local/bin/w3m")
 '(w3m-use-cookies t)
 '(wdired-allow-to-change-permissions (quote advanced))
 '(wg-mode-line-on nil)
 '(whitespace-action (quote (auto-cleanup)))
 '(whitespace-line-column nil)
 '(whitespace-style (quote (tabs trailing space-before-tab)))
 '(woman-use-own-frame nil)
 '(zenburn-bg "#3f3f3f" t)
 '(zenburn-bg+1 "#4f4f4f" t)
 '(zenburn-bg+2 "#5f5f5f" t)
 '(zenburn-bg+3 "#6f6f6f" t)
 '(zenburn-bg-05 "#383838" t)
 '(zenburn-bg-1 "#2b2b2b" t)
 '(zenburn-blue "#8cd0d3" t)
 '(zenburn-blue+1 "#94bff3" t)
 '(zenburn-blue-1 "#7cb8bb" t)
 '(zenburn-blue-2 "#6ca0a3" t)
 '(zenburn-blue-3 "#5c888b" t)
 '(zenburn-blue-4 "#4c7073" t)
 '(zenburn-blue-5 "#366060" t)
 '(zenburn-cyan "#93e0e3" t)
 '(zenburn-fg "#dcdccc" t)
 '(zenburn-fg-1 "#656555" t)
 '(zenburn-green "#7f9f7f" t)
 '(zenburn-green+1 "#8fb28f" t)
 '(zenburn-green+2 "#9fc59f" t)
 '(zenburn-green+3 "#afd8af" t)
 '(zenburn-green+4 "#bfebbf" t)
 '(zenburn-green-1 "#5f7f5f" t)
 '(zenburn-magenta "#dc8cc3" t)
 '(zenburn-orange "#dfaf8f" t)
 '(zenburn-red "#cc9393" t)
 '(zenburn-red+1 "#dca3a3" t)
 '(zenburn-red-1 "#bc8383" t)
 '(zenburn-red-2 "#ac7373" t)
 '(zenburn-red-3 "#9c6363" t)
 '(zenburn-red-4 "#8c5353" t)
 '(zenburn-region "#7f073f" t)
 '(zenburn-violet "#6c71c4" t)
 '(zenburn-yellow "#f0dfaf" t)
 '(zenburn-yellow-1 "#e0cf9f" t)
 '(zenburn-yellow-2 "#d0bf8f" t))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aquamacs-variable-width ((t (:height 140 :family "Lucida Grande"))) t))
