#+title: Piers Cawley's Literate Emacs Config
#+author: Piers Cawley
#+property: header-args:emacs-lisp :tangle yes :results silent :exports code
#+options: html-style:nil

* Why a Literate Emacs Config?

** Background
I tend to suck at writing comments, but I also tend to leave things for ages between bursts of activity, so having some way of picking up my thoughts is really handy. I want to be able to get context back when I return to a project, and I've found from the experience of [[https://bofh.org.uk/2019/02/25/baking-with-emacs/][running the bakery with emacs]] that a literate programming approach can really help.

** My Setup
There's any number of ways of setting up a literate Emacs configuration. My plan is to have this file as the Single Source Of Truth for everything emacs related that I've written and which isn't otherwise available in another package.

I'll be using XDG based paths, and placing most of the product files in ~~/.config/pdcmacs/~ and using a [[https://github.com/plexus/chemacs2][Chemacs2]] checkout in ~~/.config/emacs/~ to select this configuration.

The config is devided into the following parts.

1. Bog standard -early-init.el- setting up things like -straight.el-
2. An -init.el- with the more detailed configuration
3. Package specific support functions and configuration in a -modules/- subdirectory
4. My yasnippet snippets in -snippets/-

And, in the "nice to have" department:

1. build script to bring up Emacs how I like it
2. The various support bits and bobs to allow exporting this to my hugo-based [[https://bofh.org.uk][blog]].



** TODO Porting from legacy to Literate [1/4]

- [X] Move ~early-init.el~ to a src block
  - [X] Initial import
  - [X] Pull comments up into org-mode and break file into sections
- [ ] Move ~init.el~ to a src block
  - [ ] Initial import
  - [ ] Make more literate
- [ ] Move ~config.el~ to src block
  - [ ] Initial import
  - [ ] Break into sections
  - [ ] Merge with init.el
- [ ] Move ~modules/~ into src blocks and make literate

* Initial Setup

This only needs executing the first time you use this setup. It moves any prexisting ~~/.emacs.d/~ directory to ~~/.emacs.d.bak/~, ~~.emacs~ goes to ~~/.emacs.bak/~ and any non-chemacs2 version of ~~/.config/emacs/~ goes to ~~/.config/emacs.default/~. Execute the block using =C-c C-c=

#+begin_src sh :results silent :tangle no
  # Error out early

  set -euo pipefail
  set -o noclobber

  # Create ~/.config/emacs folder with chemacs2 in it
  if [ -d ~/.config/emacs ]
  then
      # Is it already a chemacs directory?
      if (cd ~/.config/emacs && git remote show origin | grep -q chemacs2)
      then
          echo "Chemacs2 installed!"
      else
          if [ -d ~/.config/emacs.legacy ]
          then
              echo "We already have emacs.legacy, exiting"
              exit -1
          else
              mv ~/.config/emacs ~/.config/emacs.legacy
          fi
      fi
  fi
  git clone https://github.com/plexus/chemacs2.git ~/.config/emacs/
  mkdir -p ~/.config/chemacs/
  echo >~/.config/chemacs/profiles.el <<EOF
  (("legacy" . ((user-emacs-directory . "~/.config/emacs.legacy") (server-name .  "emacs-legacy") (straight-p . t)))
   ("default" . ((user-emacs-directory . "~/.config/pdcmacs") (server-name . "pdcmacs") (straight-p . t))))
  EOF

  echo "Setting up pdcmacs folder in ~/.config"
  mkdir -p ~/.config/pdcmacs/secrets
  mkdir -p ~/.config/pdcmacs/snippets
  mkdir -p ~/.config/pdcmacs/abbrevs

  if [ -L ~/.emacs.d ] && [ -d ~/.emacs.d ]
  then
      echo "~/.emacs.d is already a symlink"
  else
      echo "Creating symlink"
      if [ -d ~/.emacs.d ]
      then
          echo "~/.emacs.d exists, moving to .emacs.d.bak"
          mv ~/.emacs.d ~/.emacs.d.bak
      fi
      ln -s ~/.config/emacs ~/.emacs.d
  fi




#+end_src

* Creating early-init.el
:PROPERTIES:
:header-args:emacs-lisp: :tangle early-init.el
:END:

I use ~~/.config/pdcmacs~ in the ~src~ block definition to tangel the file into the correct location. This file is loaded before the package system or GUI of Emacs is loaded and is ideally code that does not depend on any packages or the size of the frame.

** Turn on lexical binding and warn about editing

Your basic preamble comment

#+begin_src
  ;;; early-init.el -*- lexical-binding: t; -*-
  ;;; WARNING: This file is generated by an org file, don't edit it directly

#+end_src

**  Inhibit packages at startup
We use straight and configure it a little later.

#+begin_src
  (setq package-enable-at-startup nil)
#+end_src

** Accelerate startup some

Increasing the GC thresholds and turning off file name handlers during startup makes things a fair bit faster, so we do that. The 'proper' values will be restored by our ~emacs-startup-hook~.

#+begin_src emacs-lisp
  (let ((initial-gc-cons-threshold gc-cons-threshold)
        (initial-gc-cons-percentage gc-cons-percentage)
        (initial-file-name-handler-alist file-name-handler-alist))
    (setq gc-cons-threshold most-positive-fixnum
          gc-cons-percentage 0.6)

    (add-hook 'emacs-startup-hook
              (lambda ()
                (setq gc-cons-threshold initial-gc-cons-threshold
                      gc-cons-percentage initial-gc-cons-percentage
                      file-name-handler-alist initial-file-name-handler-alist))))

#+end_src

** Set up native compilation as we like it.

- Prefer the loading the newest compiled .el file
- Silence deferred native compilation warnings and compile asynchronously
- Drop the compiled files in ~eln-cache/~

#+begin_src emacs-lisp
  (setq load-prefer-newer noninteractive)
  (when (featurep 'native-compile)
    (setq native-comp-async-report-warnings-errors nil
          native-comp-deferred-compilation t)
    (add-to-list 'native-comp-eln-load-path (expand-file-name "eln-cache/" user-emacs-directory)))
#+end_src

** Add the mode to the frame title format

I plan to start voice coding again some time, and find it's easier to switch the coding grammar if the emacs mode is visible in the window name.

#+begin_src emacs-lisp
  (setq frame-title-format '(mode-name ":%b"))
#+end_src

** Inhibit a bunch of startup cruft

#+begin_src emacs-lisp
  (setq frame-resize-pixelwise t
        frame-inhibit-implied-resize t
        ring-bell-function 'ignore
        use-dialog-box t
        use-file-dialog nil
        use-short-answers t
        inhibit-splash-screen t
        inhibit-startup-screen t
        inhibit-x-resources t
        inhibit-startup-echo-area-message user-login-name
        inhibit-startup-buffer-menu t
        inhibit-startup-message t)

  (setq default-frame-alist
        (append default-frame-alist
                '((fullscreen . maximized)
                  (tool-bar-lines . 0)
                  (menu-bar-lines . 0)
                  (vertical-scroll-bars . nil)
                  (internal-border-width . 2)
                  (undecorated-round . t)
                  (scroll-bar-mode . -1))))

  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)

  (setq scroll-margin 0
        scroll-conservatively 100000
        scroll-preserve-screen-position 1)

#+end_src
